### ISSUE TITLE
Statusbar character not rendering properly in software with significant graphic offsets

### ISSUE THREAD

**Issue by MattFright** [kraflab/dsda-doom#118]
If it helps, I've tested this in GZDoom, Eternity, Woof, Doom Retro and DSDA, and out of those the only ones with this issue were Woof, and DSDA (but only under software renderer). Note that i only specifically tested GZDoom's OpenGL and OpenGLES renderers, though.

Attached below comparison screenshots between hardware and software in DSDA (pay attention to the %) + the wad where i discovered this issue
![doom266](https://user-images.githubusercontent.com/33336359/182060025-a01f3624-4733-4527-a399-966da6495e42.png)
![doom267](https://user-images.githubusercontent.com/33336359/182060042-54548f81-d1ee-4303-ae80-0a161e41de12.png)
[wad.zip](https://github.com/kraflab/dsda-doom/files/9230418/wad.zip)

**Comment by kraflab** [comment]
https://github.com/kraflab/dsda-doom/commit/f423db72347d8909b496d37bbb32b8e5301ddfaf
