### ISSUE TITLE
Simple shadows render as hom-like rectangles in OpenGL mode

### ISSUE THREAD

**Issue by rrPKrr** [kraflab/dsda-doom#120]
Hey!

I've been using a post 0.24.3 version of the game compiled somewhere around April, so I am not quite sure when the problem occurred exactly, but here is how simple shadows look for me in latest master branch:
![doom00](https://user-images.githubusercontent.com/110629864/182930929-fde114be-5e64-4923-b68e-61b0d474333e.jpg)

**Comment by kraflab** [comment]
I didn't even know this feature existed 🤔 
Does the problem already exist in prboom+?

**Comment by rrPKrr** [comment]
> 

No, the problem is exclusive to DSDA-Doom. It was introduced after v0.24.3. As I said I can't be more specific as to when, since I was using a build I compiled somewhere around mid April. The shadows worked properly back then.

P.S. Just to be more specific, PrBoom+ was last compiled on 29.07.2022, so this problem didn't exist there at least up to this date.

**Comment by kraflab** [comment]
My default stance on something like this is "if a feature I didn't know existed is broken, just delete it" but I imagine that's not the resolution you're looking for :^)

**Comment by rrPKrr** [comment]
Well, I mean, it's up to you to decide what to do with it as I clearly lack the needed skills to be able to fix such bugs. I can only report them to you. 😅

**Comment by kraflab** [comment]
I'll check with elim - maybe his pass over the rendering system caused this as a side effect.

**Comment by andrey-budko** [comment]
does it help?

```
diff --git a/prboom2/src/gl_shadow.c b/prboom2/src/gl_shadow.c
index a019864f..cf4444b7 100644
--- a/prboom2/src/gl_shadow.c
+++ b/prboom2/src/gl_shadow.c
@@ -246,6 +246,7 @@ void gld_RenderShadows(void)
   gl_EnableFog(false);
 
   glDepthMask(GL_FALSE);
+  glColorMask(GL_TRUE, GL_TRUE, GL_TRUE, GL_FALSE);
   glBlendFunc(GL_ZERO, GL_ONE_MINUS_SRC_COLOR);
 
   // Apply a modelview shift.
@@ -272,5 +273,6 @@ void gld_RenderShadows(void)
 
   glPopMatrix();
   glDepthMask(GL_TRUE);
+  glColorMask(GL_TRUE, GL_TRUE, GL_TRUE, GL_TRUE);
   glBlendFunc(GL_SRC_ALPHA, GL_ONE_MINUS_SRC_ALPHA);
 }

```

**Comment by rrPKrr** [comment]
Yes, these changes restore simple shadows, and now they work properly.

**Comment by kraflab** [comment]
@rrPKrr please keep future issues open until the fix is actually incorporated into the code base 😉

**Comment by kraflab** [comment]
https://github.com/kraflab/dsda-doom/commit/ba06a28350724d631838daf08338c41b97f0fa9a
@andrey-budko thanks!

**Comment by fabiangreffrath** [comment]
How come that Prboom-plus doesn't show this bug?

**Comment by kraflab** [comment]
I suspect it was a side effect from here: https://github.com/kraflab/dsda-doom/pull/105, which wasn't brought to prboom+ because of its size and how it reduces compatibility to some extent.

**Comment by fabiangreffrath** [comment]
I see, thanks!

**Comment by andrey-budko** [comment]
@fabiangreffrath because of SceneInTexture variable. It's always 'true' for dsda-doom, not only for invul effect.

Looks like replacing GL_RGBA8/GL_RGBA with GL_RGB in gl_fbo.c @ line#115 also fixes the issue, but not sure, don't remember how things work.

**Comment by fabiangreffrath** [comment]
Is this still a "can't hurt to have" fix for PrBoom+?

**Comment by andrey-budko** [comment]
I think it's safe for applying, but we always can ask @JadingTsunami to be sure

Btw, shadows code is from Risen3D:
r3d_v220-35_source.zip/../Src/rend_list.cpp/RL_RenderLID_SHADOWS

IIRC, there was some drama with Risen3D's sources, and after is was finally released, we had to take at least something from there, heh. Personally, I have never used this feature.

**Comment by JadingTsunami** [comment]
Right, PrBoom-Plus doesn't assume FBOs exist (I think they are circa 2001 or so) but looks like dsda-doom has started making this assumption. Of course this seems fine for dsda-doom; I'm only making the observation.

> Looks like replacing GL_RGBA8/GL_RGBA with GL_RGB in gl_fbo.c @ line#115 also fixes the issue, but not sure, don't remember how things work.

If the idea is to always mask the alpha channel for all writes to the FBO then sure. I just don't recall offhand if there are alpha-enabled writes to the FBO in general. I would think there are...wasn't it used for motion blur as well or am I misremembering? Or did that get removed from dsda-doom?
