### ISSUE TITLE
Micro stutter randomly occurs

### ISSUE THREAD

**Issue by Velonox** [kraflab/dsda-doom#126]
Whenever I use DSDA DOOM .24.3 and dev builds above it my game will randomly stutter and skip from frames when this does not happen in other games other than this one prboom plus, and gzdoom. I am running the game on a machine that is more than capable of running even the most demanding maps. I also run the game in opengl rendering in case that may be part of the problem. I have notice this also occurs in prboom plus, running the latest version, so the issue can be fundamental to prboom or just my pc. My pc specs are 16 gb of ram, 2080 super and a intel core i7 9700k.

**Comment by kraflab** [comment]
I see you already have the issue open in prboom-plus here: https://github.com/coelckers/prboom-plus/issues/524
As to not duplicate things, and since the issue is evidently inherited, I will close this one. Fixes from upstream get merged here.

**Comment by Velonox** [comment]
My apologize, I did not know how much synchronization there was between DSDA and prboom plus. I will keep that in mind if I ever need to open another issue going forward.
