### ISSUE TITLE
Incorrect player color translations

### ISSUE THREAD

**Issue by ghost** [kraflab/dsda-doom#130]
Hello,
Since commit https://github.com/kraflab/dsda-doom/commit/9e8abf034371b624b9cd7cf5f1f741b022d29083, the player 2's indigo translation is too bright (see screenshot here : https://cdn.discordapp.com/attachments/776233266411339786/1015726731782541312/unknown.png).

I noticed that if you revert the above commit and if you change the value 32 by the value 176 here (https://github.com/kraflab/dsda-doom/blob/master/prboom2/src/am_map.c#L90) the player translations will be fixed and the automap player arrows aswell (Red player arrow is too dark in dsda-doom compared to vanilla).

Vanilla : https://cdn.discordapp.com/attachments/237251196807675915/1015799915919724616/unknown.png
Dsda-doom : https://cdn.discordapp.com/attachments/237251196807675915/1015800270971731998/unknown.png

I have no idea how much it'll impact the dehacked translated Red/Grey monsters.

**Comment by kraflab** [comment]
Fixed by https://github.com/kraflab/dsda-doom/commit/69be072162e51a5165eb84158f14b034264e7949
