### ISSUE TITLE
FEATURE REQUEST: "Aggro-all cheat"

### ISSUE THREAD

**Issue by ghost** [kraflab/dsda-doom#135]
Hi all!

For map testing, I think it would be nice to have a cheat that changes the state of all currently idle demons to a wandering state. This would help make testing maps with teleport ambushes and such more efficient. 

Thanks!

**Comment by kraflab** [comment]
Cool idea, I'll put it on the list

**Comment by ghost** [comment]
Thanks Kraf! Been a while since i've been on GitHub, haha

**Comment by fabiangreffrath** [comment]
Indeed an interseting idea! Could probably be achieved by recursively calling `P_NoiseAlert()`. 🤔

**Comment by kraflab** [comment]
https://github.com/kraflab/dsda-doom/commit/b85fd1e07579af95f0fad75ecdd7ede0b88f422b
