### ISSUE TITLE
Music Player & .ogg files

### ISSUE THREAD

**Issue by Chonkblonk** [kraflab/dsda-doom#141]
Encountered strange error with DSDA where a .wad has an .ogg file as the music for a level.

This plays fine and causes no problems, **unless you set your music player to anything but FluidSynth,** in which case the game promptly crashes with a Signal 11 error, and it will keep happening even when you change back.
This happens even though the map in question wouldn't even be accessed normally and thus the track wouldn't even play.
Does not happen in Woof.

**Comment by kraflab** [comment]
I can't reproduce this. Please post the following:

- a link to the wad that causes the crash
- your config file that causes the crash

**Comment by Chonkblonk** [comment]
Alright, let's see here.
Link to the .wads in question:
**[https://mega.nz/folder/z9ZVEAJJ#t4IEL6VGFY7tBBMIEOKXUA](https://mega.nz/folder/z9ZVEAJJ#t4IEL6VGFY7tBBMIEOKXUA)**
Beta v0.5 has the .ogg file replaced with a MIDI file instead, but people say the error is happening still for them, so I'm not entirely sure the .ogg file is at fault, but then people reported that it worked until they changed music player from FluidSynth to another and then they get the problem.

When I use DSDA and boot up on MAP11, it runs fine. If I use IDCLEV01, it crashes immediately (I_SignalHandler: Exiting on signal: signal11), though interestingly the music will actually play, and I have FluidSynth as my default. If I use Beta v0.5 and make it start on MAP01, which now has a regular MIDI file, it will now crash on startup.

Here's my own DSDA .cfg, and another's, I can maybe provide more .cfgs later if you need a larger sample or something.
**[https://files.catbox.moe/0ximrn.zip](https://files.catbox.moe/0ximrn.zip)**

Given that it seems to happen even with a MIDI file, I'm not even certain that it's the .ogg file being a problem, but the fact that people have it not happen until they change their music player makes me think that audio or music has to be related somehow.

**Comment by Chonkblonk** [comment]
Well, I made it stop happening on my end by deleting the DeadLostSoul (DoomEdNumber 23) in MAP01.
It having no frames probably causes problems, but I'm still bewildered how the choice of music player actually affects whether or not this causes the game to crash.
Gonna ask others to test and see if it works for them and report back.

**Comment by Chonkblonk** [comment]
No, someone still reports it happening for them. Dammit.

**Comment by kraflab** [comment]
The map is crashing while reading the opengl segments. It is likely unaffected in woof because woof doesn't have a hardware renderer and wouldn't have any reason to read that data. Map 1 is also the only map that has opengl segments. Is it intentional or are they there by mistake?

**Comment by Chonkblonk** [comment]
Uh, I don't know, I've never made a map which has OpenGL segments before, or not knowingly. I don't see any lumps denoting that.
What I do remember though is that when I first made the level and made the first save, UDB kind of got 'stuck' building the nodes for like several minutes, which I thought unusual for what was really just the small room itself at the time, even large maps have only taken me a couple of seconds ever. I managed to coax it into making another save again and then it did so normally, before force killing the program.
I suppose something must have went wrong somewhere there, but I didn't experience any problems testing it out in DSDA immediately afterwards, so I didn't think much of it.

Do you think I could copy and paste all the contents into a new blank map and then resaving it to fix it, or is the map just doomed? Not exactly a high value level I couldn't live without, it's essentially a shitpost for the rare case of someone running it with the wrong port, but I kind of had fun making all the juvenile sector detail and would prefer it not going to waste.

**Comment by kraflab** [comment]
Open up the wad in slade and filter by `gl_`. You'll see that there are actually two sets of gl lumps in 0.5 denoted by `GL_MAP01` markers (I didn't check any other version, you can have a look there). To be honest, the fact that this data is duplicated with different values may be part of what is causing the crash (probably the data is for inconsistent versions of the map). As far as why the lumps are there - I don't know enough about udb. But deleting all the `GL_*` lumps should fix the problem.

**Comment by Chonkblonk** [comment]
Oooh, right, a couple of submissions had those additional lumps but I didn't think much of them, just included them because they were there. I'll check this out.

**Comment by Chonkblonk** [comment]
It would appear that the GL lumps was the solution. I'm very puzzled though, because of how the music player somehow affected people's outcome.

**Comment by kraflab** [comment]
These kinds of crashes are caused by reading the wrong location in memory. Depending on how memory is allocated (which can change between launches of the game and between different configurations), you could get "lucky" and read a location that doesn't cause a crash.
