### ISSUE TITLE
UMAPINFO Par times do not work (without dehacked)

### ISSUE THREAD

**Issue by Mabadman** [kraflab/dsda-doom#142]
Setting par times with UMAPINFO doesn't seem to work. If set, the map will simply not show a par time for the map.
Only way to get it to work is to create a DEHACKED lump and set a par time for any map. Once the par time is set, regardless of which map it is, par times set by UM will work as intended.

WADs used for testing:
[umapinfo.zip](https://github.com/kraflab/dsda-doom/files/9669110/umapinfo.zip)

**Comment by kraflab** [comment]
Please raise this issue in the parent repository so that it can be fixed at the source: https://github.com/coelckers/prboom-plus/issues

**Comment by Mabadman** [comment]
You're right, I thought PrBoom+ was working fine in this regard but it doesn't seem to. I'll create an issue there.
