### ISSUE TITLE
Can't slide automap in 0.24.3

### ISSUE THREAD

**Issue by cmhobbs** [kraflab/dsda-doom#144]
When I open the automap, I am unable to slide the map around.  I have tried with the default arrow keys and I've tried reassigning them to other keys but the map never moves when I press them.  I am able to zoom with the mouse wheel, though.  Am I missing a setting somewhere?

Thanks!

**Comment by kraflab** [comment]
Have you tried toggling follow mode?

**Comment by cmhobbs** [comment]
That was the issue.  I thought I had toggled it before but I overlooked it.  Thanks for the response and sorry for the silly question!
