### ISSUE TITLE
GL_RGB5_A1 causes palette distortions in Indexed lighting mode

### ISSUE THREAD

**Issue by rrPKrr** [kraflab/dsda-doom#148]
Hey! The new indexed lighting mode is absolutely amazing! Had some issues with palette the first time I launched the game though. It seems like it's texture format "gl_rgb5_a1" that doesn't work nicely with the new mode.

**Comment by kraflab** [comment]
I don't know much about the texture format option. Is there a wad that doesn't work at all, or is it just that the texture format option should be restricted?

**Comment by rrPKrr** [comment]
Check this out: https://doomwiki.org/wiki/Frozen_Time

Basically, it works for 95% of the wad, but there are a few textures that don't show properly (including titlepic).

**Comment by kraflab** [comment]
Oh the hi-res stuff. I think xaser mentioned this requires the shaders light mode and isn't working in the indexed mode, so this is just a limitation. Maybe we can detect the presence of those textures and adjust the mode automatically or warn the player in such cases.

**Comment by XaserAcheron** [comment]
Welp, it's supposed to switch off the high-res texture stuffs in indexed mode -- I had that working at some point but either it broke or I missed a spot or two. Will take a look.
