### ISSUE TITLE
Spectres appear on top of pain palette in Indexed light mode

### ISSUE THREAD

**Issue by kraflab** [kraflab/dsda-doom#152]
See screenshot reported by Vile.

![doom01](https://user-images.githubusercontent.com/25529060/200792415-e6c1d467-e816-4db6-9906-ec0f9544fdbc.png)

**Comment by andrey-budko** [comment]
Another example from Vile's stream - invul affects automap colors

![image](https://user-images.githubusercontent.com/6490190/201211876-247a28eb-12da-4da1-abdf-f7db41d09927.png)

**Comment by andrey-budko** [comment]
And this with mlook and gamma correction (something with gld_DrawSkyCaps)

![image](https://user-images.githubusercontent.com/6490190/201213844-de2944a5-ea03-45dd-8304-0518ee3529ed.png)

**Comment by rrPKrr** [comment]
Simple shadows also render on top of pain palette:
![palette](https://user-images.githubusercontent.com/110629864/201447018-9f3bd4e3-9bc3-4a9b-b458-bc6ea4c136a6.jpg)

**Comment by rrPKrr** [comment]
In complevels 7-21 bullet puffs, teleporter sprites, projectiles render in red color depending on the distance/lighting (both?) of the affected sprite (e4m1):
![palette_shift1](https://user-images.githubusercontent.com/110629864/201448280-750cacdf-acd2-4a51-9ab8-5873944c1d4e.jpg)
![palette_shift2](https://user-images.githubusercontent.com/110629864/201448282-f8383dac-22f5-47a4-a394-1d4532dfe1e8.jpg)

**Comment by kraflab** [comment]
That sprite stuff only happens when `boom_translucent_sprites` is on (which is probably why you only saw it in higher complevels). The weird thing is I can't get it to happen at all on e1m1, but it happens easily on e4m1. Maybe something with the tranmap?

**Comment by rrPKrr** [comment]
> The weird thing is I can't get it to happen at all on e1m1, but it happens easily on e4m1. Maybe something with the tranmap?

I have a crazy theory... 😄 It happens only on maps which have specters. Add a specter to e1m1 for example here and some magic will happen.
![specter](https://user-images.githubusercontent.com/110629864/201491679-e33ca920-8812-457c-8f48-132ea5323bcd.jpg)

P.S. Yeah, sprites break if camera directs at specters (or their sprite X axis or something, regardless if they can be seen or are somewhere else on that map):
![theory](https://user-images.githubusercontent.com/110629864/201491969-26083410-cbcd-4ade-acf9-d287fbdd8c9e.jpg)

P.P.S. Something to do with this code here: https://github.com/kraflab/dsda-doom/blob/master/prboom2/src/gl_main.c#L2684-L2685

**Comment by kraflab** [comment]
So this must be happening when the fuzz shader gets applied 🤔 
Maybe the fuzz is applied before the color lookup happens that converts to the final color? (Although then I still don't know why the fuzz shader would affect non-fuzz.)

**Comment by rrPKrr** [comment]
Yeah, you are right... While not a fix but simply turning off fuzz shader makes everything render properly.

P.S. Noticed that if you simply comment out glsl_SetFuzzShaderActive() in gld_DrawSprite(), then fuzz effect stops working but it fixes the bug. But if you'll add glsl_SetFuzzShaderInactive() right after glsl_SetFuzzShaderActive(), then only fuzz effect will stop working. But the bug will still be present.

**Comment by rrPKrr** [comment]
Should fix the problem:

void glsl_SetFuzzShaderInactive()
{
  if (active_shader == sh_fuzz)
  {
    if (V_IsWorldLightmodeIndexed())
    {
      GLEXT_glUseProgramObjectARB(sh_indexed->hShader);
      active_shader = sh_indexed;
    }
    else
    {
      GLEXT_glUseProgramObjectARB(0);
      active_shader = NULL;
    }
  }
}

**Comment by kraflab** [comment]
Applied rrPKrr's fix for translucent sprites and a tentative fix for the automap issue.
