### ISSUE TITLE
PortMidi volume spikes

### ISSUE THREAD

**Issue by kraflab** [kraflab/dsda-doom#153]
Reported by zeromaster on discord:

There is occasionally a music volume spike when quitting dsda-doom. Also happens when entering the intermission screen. It only happens with PortMidi and not when using FluidSynth.

**Comment by kraflab** [comment]
@ceski-1 any idea why this might happen?

**Comment by ceski-1** [comment]
Is there any additional information such as wad, dsda-doom version, PortMidi device (MS GS Wavetable Synth or other), operating system?

**Comment by kraflab** [comment]
More details from zm:

> I use windows 11, no idea about portmidi device, I tried different settings and it seems to happen much more often with tntmidi.wad for example, default config with portmidi instead of fluidsynth.. the length of the spike is seems to vary a bit, but it's really short, and the loudness varies quite a bit too, it was definitely a lot louder last time, but still quite noticeable now
> 
> so -iwad doom2 -file tntmidi and just starting up and quitting or exit map01 will cause it to happen, usually within 5-10 tries

**Comment by ceski-1** [comment]
This should fix the problem: https://github.com/ceski-1/dsda-doom/commit/70adfd3d9567ac0c44d010037ed7185efd20f073

Please ask zeromaster to give this a try. I can make a PR here or upstream if everything is good.
[dsda-doom-20221113-test-win64.zip](https://github.com/kraflab/dsda-doom/files/9998716/dsda-doom-20221113-test-win64.zip)

**Comment by kraflab** [comment]
ZM has confirmed that the issue is fixed with that build 👍 
Since you already have a branch set up, you may as well open the PR here. I will ping fabian as well.
