### ISSUE TITLE
UMAPINFO: default endpic for E2M8 supposed to be "VICTORY2"?

### ISSUE THREAD

**Issue by fabiangreffrath** [kraflab/dsda-doom#160]
https://github.com/kraflab/dsda-doom/blob/33b6ea095985365c5175f966818cdc6c61c413ff/prboom2/src/umapinfo.cpp#L691

Compare with:
https://github.com/kraflab/dsda-doom/blob/33b6ea095985365c5175f966818cdc6c61c413ff/prboom2/src/f_finale.c#L790-L792

**Comment by kraflab** [comment]
There is no "victory" lump in doom.wad so I'd agree this should be victory2 😅

**Comment by kraflab** [comment]
https://github.com/kraflab/dsda-doom/commit/e59c6394b0e161dee0447a60e101a8887c23bc83

**Comment by fabiangreffrath** [comment]
Yep, I just checked: Pr+ errors out if you finish E2M8 with a minimal UMAPINFO lump that does not set an endpic or a next map for that map. How old is that code you say?
