### ISSUE TITLE
[0.24.3] Random crashes with Rewind in Jumpwad MAP07

### ISSUE THREAD

**Issue by Beed28** [kraflab/dsda-doom#162]
Been having fun with a fairly recent map pack, [Jumpwad](https://www.doomworld.com/vb/thread/129577). It's been pretty fun (if confusing at times), and that Rewind button has been very handy throughout. But at some point in MAP07, it's started triggering "Corrupt savegame" crashes at complete random.

It's been happening the most frequent when attempting the island near the north-west, with the meteors. There doesn't seem to be any log whenever it crashes.

![image](https://user-images.githubusercontent.com/30600723/206878146-3fcb7d6e-21ea-489a-aa8c-1f27f7059797.png)

**Comment by kraflab** [comment]
I fixed a corrupt savegame bug for 0.25, so this may already be fixed, but it needs confirmation.

**Comment by kraflab** [comment]
Rayziik did a bunch of testing and couldn't get a crash on the latest dev build, so it does appear to be fixed. Thanks for the report.
