### ISSUE TITLE
Request.

### ISSUE THREAD

**Issue by ghost** [kraflab/dsda-doom#165]
Hello.

DSDA doom when played at 320×200 resolution with fullscreen mode played with Software Renderer looks way much different than the same resolution, with fullscreen mode played on OpenGL renderer.

So, in future releases can you please let the resolution of 320×200 of OpenGL renderer, look similar to the Software Renderer's 320×200 resolution ?

**Comment by kraflab** [comment]
This has already been done for 0.25. If you have issues with that eventual release, feel free to reopen the issue.

**Comment by ghost** [comment]
So, are you going to make OpenGL's 320×200 resolution look like Software Renderer or the way around ?

**Comment by kraflab** [comment]
opengl will work like software

**Comment by ghost** [comment]
Ok thank you sir.🙏
