### ISSUE TITLE
[Feature request] 4:3 aspect ratio HUD for 16/21:9 aspect ratios

### ISSUE THREAD

**Issue by El-Juancho** [kraflab/dsda-doom#169]
For version 25.0 can we have an option to have a "4:3 hud" (messages, advanced/extended HUD, coordinate display etc) option for 16:9/21:9 users? I have a new 21:9 screen and now the hud is way too far from the center of the screen and i would like it to be like in 4:3 mode. 

I have created this image to show how I would like this to look like :)
![e](https://user-images.githubusercontent.com/70743149/208015428-b562aba4-ff23-43e7-868f-43b4eb9ee1a4.png)

**Comment by ghost** [comment]
@kraflab 
But please keep original hud in the quality of life settings as it is i.e in version 0.24.3
Please keep this above hud ( that El Juancho said ) optional.
Just a humble request.🙏

**Comment by kraflab** [comment]
The position of all the hud elements is already fully customizable in 0.25. If you have any issues on release feel free to reopen this issue.

**Comment by BonyBastard300** [comment]
Hmm, yeah, I noticed you kicked me from Discord without any warning.. fair enough..
