### ISSUE TITLE
[FReq] Have 2 max pitch options, one for software, and one for hardware.

### ISSUE THREAD

**Issue by yum13241** [kraflab/dsda-doom#172]
Why? Because having 90 degree pitch in Software is not only a lie (because you'd need infinite processing power) but it's also pointless, since things get very distorted. OTOH, in OpenGL it's annoying not to be able to look ALL the way down and it's very noticeable. An alternative would be to ignore this value in Software.

btw "Light Mode" "Shader" is way too bright, and GLBoom is very dark.

**Comment by kraflab** [comment]
In general I prefer to have software and hardware consistent from a perspective of mechanics. Maybe I'll reconsider this in the future though.

All light modes have a gamma setting like in software. You can adjust the brightness to your liking.

**Comment by yum13241** [comment]
Try setting max pitch to 90 degrees in software and tell me wether you like it or not. It gets so distorted that it's pointless. On OpenGL it makes sense though since you can actually see meaningful information there.

It's annoying to have to change the max pitch when I change renderers.


Also 90 degrees is straight up IMPOSSIBLE in software so you're lying to the user. Every other port that has free look enforces a meaningful look cap on software and ignores it in hardware.

I understand your desire but it kinda doesn't make sense, since 89.9 degree look in software is pointless.
