### ISSUE TITLE
[Bug] Projectiles cannot be seen when translucency filter is set to 0.

### ISSUE THREAD

**Issue by yum13241** [kraflab/dsda-doom#173]
This bug caused me frustration, because I wanted to disable translucency, (it looks fugly) so I set it to zero. This makes all projectiles invisible. It should just refuse and say "Out Of Range", just like when you try to set the sound channels higher than 32.

Setting it to 100 gives the desired effect.

User error, but the program should yell at the user.

**Comment by kraflab** [comment]
This isn't a bug and is working as intended. It also doesn't matter because that slider doesn't exist in 0.25. If you have any issues after the release, feel free to open a new issue.

**Comment by yum13241** [comment]
So when I get 0.25 I can't disable translucency.
