### ISSUE TITLE
Fullclip cheat doesn't work properly with MBF21 pointer A_ConsumeAmmo

### ISSUE THREAD

**Issue by Beed28** [kraflab/dsda-doom#182]
The newly added Fullclip cheat works great with the default Doom weapons, but it doesn't seem to work as great with custom MBF21 weapons, particularly ones that call A_ConsumeAmmo as part of the firing sequence.

For most part, the pointer will still drain ammo even with it active, but in most cases the weapon can still be fired after running out. One exception is the BFG replacement in [Vesper](https://www.doomworld.com/forum/topic/123800-v100-vesper-mbf21-showcase-mod/), which loses its continuous firing after running out.

**Comment by kraflab** [comment]
Fixed in https://github.com/kraflab/dsda-doom/commit/83c8de19e8e6f692a31e04805a0ac8d2353359e9
