### ISSUE TITLE
Load order is different when launching game normally to launching a demo lmp

### ISSUE THREAD

**Issue by erik1083** [kraflab/dsda-doom#184]
When launching a demo, the PWAD is loaded before the doom2 patches.

---OUTPUT FROM LAUNCHING GAME NORMALLY---
D:\Doom\dsda-doom>dsda-doom.exe -iwad doom2 -file ..\doomWADdir\STRG.wad -cl 2

dsda-doom v0.25.2 (https://github.com/kraflab/dsda-doom/)
dsda-doom is released under the GNU General Public license v2.0.
You are welcome to redistribute it under certain conditions.
It comes with ABSOLUTELY NO WARRANTY. See the file COPYING for details.

Playing: DOOM 2: Hell on Earth
 adding D:\Doom\doomWADdir/doom2.wad
 adding D:\Doom\dsda-doom/dsda-doom.wad
 adding D:\Doom\dsda-doom/autoload/doom-all/Doom_Sound_Bulb.wad
 adding D:\Doom\dsda-doom/autoload/doom-all/doom_wide.wad
 adding D:\Doom\dsda-doom/autoload/doom2.wad/D2SPFX20_beta2.WAD
 **adding D:\Doom\dsda-doom/..\doomWADdir\STRG.wad**
 adding D:\Doom\dsda-doom/autoload/STRG.wad/strg_mus.wad
 adding D:\Doom\dsda-doom/autoload/STRG.wad/strg_wide.wad
Loading DEH lump from D:\Doom\dsda-doom/autoload/STRG.wad/strg_wide.wad
Loading DEH file D:\Doom\dsda-doom/autoload/doom-all/blood_color.deh
Loading DEH file D:\Doom\dsda-doom/autoload/doom2.wad/D2DEHFIX.DEH
Loading DEH lump from D:\Doom\dsda-doom/..\doomWADdir\STRG.wad
Loading DEH file D:\Doom\dsda-doom/autoload/STRG.wad/doom_colored_blood.deh

---OUTPUT FROM LAUNCHING A DEMO VIA DOUBLE CLICK---
D:\Doom\LMP\Struggle>sg11-602.lmp

dsda-doom v0.25.2 (https://github.com/kraflab/dsda-doom/)
dsda-doom is released under the GNU General Public license v2.0.
You are welcome to redistribute it under certain conditions.
It comes with ABSOLUTELY NO WARRANTY. See the file COPYING for details.

Playing: DOOM 2: Hell on Earth
 adding D:\Doom\dsda-doom/dsda-doom.wad
 adding D:\Doom\doomWADdir/DOOM2.wad
 **adding D:\Doom\doomWADdir/strg.wad**
 adding D:\Doom\dsda-doom/autoload/doom-all/Doom_Sound_Bulb.wad
 adding D:\Doom\dsda-doom/autoload/doom-all/doom_wide.wad
 adding D:\Doom\dsda-doom/autoload/DOOM2.wad/D2SPFX20_beta2.WAD
 adding D:\Doom\dsda-doom/autoload/strg.wad/strg_mus.wad
 adding D:\Doom\dsda-doom/autoload/strg.wad/strg_wide.wad
Loading DEH lump from D:\Doom\dsda-doom/autoload/strg.wad/strg_wide.wad
Loading DEH file D:\Doom\dsda-doom/autoload/doom-all/blood_color.deh
Loading DEH file D:\Doom\dsda-doom/autoload/DOOM2.wad/D2DEHFIX.DEH
Loading DEH lump from D:\Doom\doomWADdir/strg.wad
Loading DEH file D:\Doom\dsda-doom/autoload/strg.wad/doom_colored_blood.deh

Playing demo:
  Name: D:\Doom\LMP\Struggle\sg11-602.lmp
  Compatibility: Doom/Doom2 v1.9

**Comment by kraflab** [comment]
https://github.com/kraflab/dsda-doom/commit/72a681a30e2547c708853250497714afea3f8e6a
