### ISSUE TITLE
icon available in SVG format (or resized to reasonable dimensions)

### ISSUE THREAD

**Issue by fabiangreffrath** [kraflab/dsda-doom#185]
Hi,

I am currently packaging dsda-doom to replace prboom-plus in Debian, and in the course of this I found that dsda-doom lacks an icon in SVG format and only ships one in PNG format with very odd 2002x2104 dimensions. Would it be possible to add an icon in SVG format?

 - Fabian
 -

**Comment by kraflab** [comment]
I have the source photoshop file, but I don't know how to create anything out of it 😉
If you know how to do it, I can send you the file.

**Comment by fabiangreffrath** [comment]
I am not sure if I can do anything with a photoshop file, as I don't own that software, and I don't know if GIMP can read it (we could try it out). But, the person that created it could possibly export it in SVG format?

**Comment by fabiangreffrath** [comment]
> I don't know if GIMP can read it

Some tutorials suggest it should work. So, could you please send me the photoshop file? Thanks!

**Comment by fabiangreffrath** [comment]
To explain my dilemma a bit, this is the icon directory on a typical Debian installation (i.e. mine):

```
$ ls -l /usr/share/icons/hicolor/
insgesamt 152
drwxr-xr-x 15 root root  4096 22. Aug 2019  128x128
drwxr-xr-x 15 root root  4096 21. Dez 09:11 16x16
drwxr-xr-x 15 root root  4096 22. Aug 2019  192x192
drwxr-xr-x 15 root root  4096 21. Dez 09:11 22x22
drwxr-xr-x 15 root root  4096 21. Dez 09:11 24x24
drwxr-xr-x 15 root root  4096 21. Sep 2019  256x256
drwxr-xr-x 15 root root  4096 21. Dez 09:11 32x32
drwxr-xr-x 15 root root  4096 22. Aug 2019  36x36
drwxr-xr-x  3 root root  4096  4. Sep 2019  42x42
drwxr-xr-x 15 root root  4096 21. Dez 09:11 48x48
drwxr-xr-x 15 root root  4096 22. Aug 2019  512x512
drwxr-xr-x 15 root root  4096 22. Aug 2019  64x64
drwxr-xr-x 15 root root  4096 22. Aug 2019  72x72
drwxr-xr-x  3 root root  4096  4. Sep 2019  8x8
drwxr-xr-x 15 root root  4096 22. Aug 2019  96x96
-rw-r--r--  1 root root 28128 29. Dez 16:01 icon-theme.cache
-rw-r--r--  1 root root 55507 18. Mär 2018  index.theme
drwxr-xr-x 15 root root  4096 22. Aug 2019  scalable
drwxr-xr-x  3 root root  4096 29. Aug 16:43 symbolic
```

As you can see, you have the choice to install icons as pixel data with multiples-of-(powers-of)-two dimensions (in PNG format) or as scalable data (in SVG format).

Generally, I prefer the latter. I could live with the original dsda-doom icon in PNG format, but obviously with its oddball dimensions it doesn't fit into any of the categories. I could resize it myself and add it to my packaging, but then my packaging and the original source distribution would have a binary difference -- which if frowned upon in Debian. Thus, I am asking for the icon in SVG format, which is XML data under the hood and is thus easily added to the packaging although it is not (yet) part of the original source distribution.

**Comment by fabiangreffrath** [comment]
Alternatively, it would help if you could resize the PNG icon to e.g. 512x512 px (and probably keep the original file in a separate repository)?

**Comment by KAMiKAZOW** [comment]
> If you know how to do it, I can send you the file.

Personally, I'm of the opinion source files of graphics should be treated like text source code by open source projects and just put alongside the converted. So how about you upload it here and I'll look what I can do with Affinity Photo which I have. Please tag me once you did.

**Comment by kraflab** [comment]
Going to close this as the immediate need was met offline and the original artist confirmed that SVG is not possible from the existing source. I'll commit the files at some point anyway.

**Comment by fabiangreffrath** [comment]
Tada, with the help of png2svg and svgo:

![dsda-doom](https://user-images.githubusercontent.com/6449237/232701875-626851d3-1cb8-46f6-96c5-64146975ab2f.svg)

**Comment by fabiangreffrath** [comment]
@kraflab Would you add this SVG format icon to the repository next to the PNG format icon, please?

**Comment by fabiangreffrath** [comment]
> @kraflab Would you add this SVG format icon to the repository next to the PNG format icon, please?

... or should I file a PR?
