### ISSUE TITLE
Fluidsynth sample-rate out of range

### ISSUE THREAD

**Issue by BlipBlerp** [kraflab/dsda-doom#191]
I've been having this issue where Fluidsynth seems to be ignoring my settings. This only happens to me on 0.25.x. I have deleted my cfg multiple times but it keeps happening. These are my sound settings:
```
# Sound settings
snd_pcspeaker                  0
pitched_sounds                 0
full_sounds                    0
snd_samplecount                512
snd_samplerate                 44100
sfx_volume                     1
music_volume                   1
mus_pause_opt                  1
snd_channels                   32
snd_midiplayer                 "fluidsynth"
snd_soundfont                  "RLNDGM.SF2"
snd_mididev                    ""
mus_fluidsynth_chorus          0
mus_fluidsynth_reverb          0
mus_fluidsynth_gain            50
mus_opl_gain                   50
mus_portmidi_reset_type        "gs"
mus_portmidi_reset_delay       0
mus_portmidi_filter_sysex      1
mus_portmidi_reverb_level      40
mus_portmidi_chorus_level      0
```

Whenever I launch dsda-doom I get this error message in the console logs, which I guess could be related
```
fluidsynth: error: requested set value for 'synth.sample-rate' out of range
fl_init: Couldn't set synth.sample-rate
```

**Comment by kraflab** [comment]
@ceski-1 do you have any idea about this one?

**Comment by ceski-1** [comment]
I can reproduce this by setting my sound card's sample rate to 192kHz. Setting it to 48kHz is fine. If I compile with MSYS2 (MinGW 64-bit), to grab newer versions of FluidSynth, etc., I can use any sample rate and there's no error. I'll take a closer look in a bit.

**Comment by ceski-1** [comment]
Here's the problem: https://github.com/kraflab/dsda-doom/blob/144709bf29dc8477220e3c9cdd6ed37786861385/prboom2/src/SDL/i_sound.c#L787

Here's what `Mix_QuerySpec()` returns for `snd_samplerate` for different versions of SDL2 with `snd_samplerate 44100` in the config and the sound card set to 192kHz:

| SDL2 ver. | Mix_QuerySpec() |
| --- | --- |
| 2.0.18 | 44100 |
| 2.0.20 | 44100 |
| 2.0.22 | 192000 |
| 2.24.0 | 192000 |
| 2.24.1* | 192000 |
| 2.24.2 | 192000 |
| 2.25.1 | 44100 |
| 2.26.0 | 44100 |
| 2.26.1 | 44100 |
| 2.26.2 | 44100 |

*Bundled with dsda-doom 0.25.6.

FluidSynth only supports up to 96kHz, hence the error. Maybe just remove the `Mix_QuerySpec()` line in case SDL2's behavior changes again. Also, maybe bump this up to 96000 max:

https://github.com/kraflab/dsda-doom/blob/c3d4129a3146b250bc24cf9accfd85d22477a32a/prboom2/src/dsda/configuration.c#L693

**Comment by ceski-1** [comment]
More info on why that line was added by Fabian: https://github.com/coelckers/prboom-plus/commit/c96f970f18bc6f2e5b7b71aa6df8080d1af65934

**Comment by fabiangreffrath** [comment]
Some more background:
https://github.com/FluidSynth/fluidsynth/issues/623

**Comment by ceski-1** [comment]
Maybe the best solution for now is to update the libraries before the next release.

**Comment by kraflab** [comment]
Alright then, will make sure to update this one next time.

**Comment by kraflab** [comment]
@ceski-1 I checked the last release and it's 2.3.0. How did you detect 2.24.1? I double checked the package in my dev environment and also the dll and both are 2.3.0.

**Comment by ceski-1** [comment]
Extract last release (dsda-doom-0.25.6.zip), right-click SDL2.dll -> Properties -> Details -> 2.24.1.

**Comment by rfomin** [comment]
> I double checked the package in my dev environment and also the dll and both are 2.3.0.

You probably meant fluidsynth.dll The latest version of SDL2 is 2.26.4

**Comment by kraflab** [comment]
Oh whoops 🤦

**Comment by kraflab** [comment]
Gonna close this as it's resolved for the next release. Thanks again for investigating this.
