### ISSUE TITLE
textured automap issue when rendering resolution is smaller than the display resolution

### ISSUE THREAD

**Issue by liPillON** [kraflab/dsda-doom#193]
Hi! 
I usually play at 1280x720 in OpenGL mode, non exclusive fullscreen.
My laptop has a full hd panel so dsda scales the 720p rendered frame up to the 1080p screen resolution.

Today using 0.25.4 win64 I discovered an issue with the textured automap which seems to be triggered by the setup described above.

It seems that the area covered by textures is limited to the 1280x720 rendering resolution, leaving untextured the remaining corners of what's visible at my 1920x1080 display resolution.
The issue is present in both exclusive and non-exclusive fullscreen modes.
It manifests regardless of the opengl light mode settings and regardless overlay mode status.

It goes away when switching to windowed mode (when both rendering and presentation resolution are the same).

The system runs Win10 21H2 x64 and uses Intel graphic drivers provided by windows update.
The integrated GPU is a gen9 UHD620.

Some screenshots taken using the port's builtin feature:

[fullscreen-normal](https://user-images.githubusercontent.com/48625273/211863077-c89e8d63-285b-40c5-b9e7-8040a4d30631.png)

[fullscreen-overlay](https://user-images.githubusercontent.com/48625273/211863222-4ae631f2-b80a-486d-9dfe-fe9388ba80ee.png)

[windowed-normal](https://user-images.githubusercontent.com/48625273/211863247-31cecc24-e042-4853-b436-cc7021e98eb9.png)

[windowed-overlay](https://user-images.githubusercontent.com/48625273/211863261-22a357ff-eef8-4b42-8f32-c98c58a2cf48.png)

**Comment by kraflab** [comment]
Thanks for the detailed description and images, we'll take a look.
