### ISSUE TITLE
Add option to select MIDI device

### ISSUE THREAD

**Issue by Kappa971** [kraflab/dsda-doom#194]
Hi, it would be useful to have in the DSDA-Doom options the possibility to select the desired MIDI device (for example to use Sound Canvas VA).
Currently, compiling DSDA-Doom with MSYS2 (mingw64) and selecting Portmidi, the game will always use the Microsoft GS synthesizer, despite having set in Coolsoft MIDIMapper Sound Canvas VA as the default device.
Instead, compiling DSDA-Doom in Visual Studio and selecting Portmidi in the game settings, the game takes into account the device set in the MIDIMapper.

**Comment by ceski-1** [comment]
Compiling with MSYS2 and using CoolSoft MIDIMapper works for me. You can also change `snd_mididev` in the .cfg to your preferred device (e.g. "loopMIDI Port").

**Comment by Kappa971** [comment]
> Compiling with MSYS2 and using CoolSoft MIDIMapper works for me. You can also change `snd_mididev` in the .cfg to your preferred device (e.g. "loopMIDI Port").

I found the precompiled version here https://www.doomworld.com/forum/topic/133096-dsda-doom-v0254-2023-01-10/ and it works fine (I assume it was compiled with MSYS2). This means that probably, in the version that I compiled by myself, some dependencies are missing. Reading the documentation I don't understand what is missing (is it updated?)
```
1. To compile DSDA-Doom, you need at least SDL2. To enable various
     extensions and optional features, the following are required:
     - SDL2_image (for high-res textures in OpenGL, and PNG screenshots)
     - for music support, some or all of
       * SDL2_mixer (midi, timidity)
       * Fluidsynth (midi)
       * Portmidi (midi)
       * MAD (mp3)
       * DUMB (various tracker-style formats)
       * vorbisfile (ogg)
     On a typical Debian or Ubuntu system this may be sufficient:
       apt-get install libsdl2-dev libsdl2-image-dev \
         libsdl2-mixer-dev libfluidsynth-dev \
         libportmidi-dev libmad0-dev libdumb1-dev libvorbis-dev

    You will also need `cmake` and `make` if you haven't already got them.

```
but between my MSYS2 build and the official one I notice that in the official one there are many more dlls.

**Comment by Kappa971** [comment]
> Compiling with MSYS2 and using CoolSoft MIDIMapper works for me. You can also change `snd_mididev` in the .cfg to your preferred device (e.g. "loopMIDI Port").

I reinstalled the dependencies and now it works.
If adding an option to choose MIDI device in the game menu is not in the plans, I can close this problem.
