### ISSUE TITLE
Some OpenGL rendering glitch

### ISSUE THREAD

**Issue by NuruTheDoomer** [kraflab/dsda-doom#196]
The wall that should hide the lowering bar in this area is glitchy and just straight up disappear, revealing parts of the bar that shouldn't be visible

WAD & Map : [Sunder 2407.wad](https://www.dropbox.com/s/vi47z1a4e4c4980/Sunder%202407.zip?dl=1), MAP31

Here is what it looks like in 0.24.3
![0.24.3](https://user-images.githubusercontent.com/110539563/213229413-7d24bf6a-5e85-43aa-a597-9dabcce27584.png)

And here is in 0.25.4
![0.25.4](https://user-images.githubusercontent.com/110539563/213232106-b6121bfc-115e-483f-9282-2e52d34016c8.png)

[Here is also a video of the bug in action](https://www.youtube.com/watch?v=OLGKBy6lJHY)

The lighting mode for both instances are the Shaders mode

**Comment by bkoropoff** [comment]
Looks like Z fighting between the upper and lower textures.
