### ISSUE TITLE
Autoload hud files

### ISSUE THREAD

**Issue by RamonUnch** [kraflab/dsda-doom#197]
I have played around a little with the creation of custom hud files, I think it is quite powerful and well designed, however it seems there is no way to autoload simple ASCII hud files that are specified via the `-hud` parameter.

I suggest that any file with the `.hud` extension in the auto-load folder would be candidate for loading as a hud file, like this someone could easily customize their own huds without having to go through the trouble of creating a wad file.

**Comment by fabiangreffrath** [comment]
What if you rename your file to `dsdahud.lmp`?

**Comment by RamonUnch** [comment]
Sorry for my ignorance, I read the source and I realized that dsda-doom already loads `.lmp` files, I will inform people from the doomworld forums.
Excuse me for the unnecessary issue.
