### ISSUE TITLE
[Suggestion] Automap title color

### ISSUE THREAD

**Issue by OpenRift412** [kraflab/dsda-doom#198]
I could've sworn there was an option for this already, but I couldn't find this anywhere in the menus or in the config file either. Am I missing something?

**Comment by kraflab** [comment]
That's one of the settings that was not migrated when I rewrote the config system. I haven't decided yet what I want to do with the map text and other text not yet covered by the new hud definition system. Once it's all migrated then it will be configurable somewhere.

**Comment by kraflab** [comment]
This has been completed for 0.26

**Comment by OpenRift412** [comment]
@kraflab I checked both the menus and the cfg file and don't see where to change this setting. What am I missing here?

**Comment by kraflab** [comment]
https://github.com/kraflab/dsda-doom/blob/master/docs/text_color.md

**Comment by OpenRift412** [comment]
> https://github.com/kraflab/dsda-doom/blob/master/docs/text_color.md

I see... well if that's the case then making the default title color red would probably be best.
