### ISSUE TITLE
request if possible, mods?

### ISSUE THREAD

**Issue by DOOMMARINE117** [kraflab/dsda-doom#203]
can mods be added in like alien eradication, castlevania, zblood, heretic, hexen, rekkr, star wars, gameplay modfications too like relighting, bunch of others? if possible?

**Comment by kraflab** [comment]
Your list has a lot of different types of things. Heretic is a game, not a mod, and it's already supported. The same goes for hexen. Rekkr is an iwad and it's supported. All major source ports support mods. If you need a guide on the basics of playing doom with a source port, you should be able to find some options via google. A launcher may also help out - there are plenty of options to choose from.
