### ISSUE TITLE
"Orphan mobj in msecnode list" message spam when playing demos with ghosts

### ISSUE THREAD

**Issue by NuruTheDoomer** [kraflab/dsda-doom#206]
Just trying out the ghost feature after a long time, and after the demo finishes I saw that the console got spammed with this message...
![image](https://user-images.githubusercontent.com/110539563/216541667-12b72eda-84d3-493f-b81b-0b1fcdc45e83.png)
...all the way until the end of the demo playback

WAD : [thtthren.wad](https://dsdarchive.com/files/wads/doom2/2868/thtthren.zip)
[Demo & Ghost Files](https://github.com/kraflab/dsda-doom/files/10576664/The.Demo.and.Ghost.Files.idk.zip)

Not sure whether this is a new bug or its the same thing as the NERF MAP08 message spam

**Comment by kraflab** [comment]
Discussed on discord: this isn't a bug. Maybe the log level should be updated or ignored for ghost data, but it's the right behaviour.
