### ISSUE TITLE
Custom colormap error in indexed light mode

### ISSUE THREAD

**Issue by kraflab** [kraflab/dsda-doom#207]
https://www.doomworld.com/forum/topic/130661-hellcinerator-definitive-edition-feb-2023-large-mbf21-map/

![dsda-colourmap-example-2](https://user-images.githubusercontent.com/25529060/217593037-8302d5c4-d3ca-4325-bfc9-fb59542e4876.png)

**Comment by bkoropoff** [comment]
This fixes itself if you switch to software mode and back to OpenGL, so I suspect a colormap texture is being cached and not cleared on a colormap change.

**Comment by kraflab** [comment]
@bkoropoff have you looked into this more? I will start investigating after my current task is done, but I don't want to step on your toes.

**Comment by bkoropoff** [comment]
I haven't looked at it beyond finding that something gets reset on re-init of GL.

**Comment by kraflab** [comment]
- the colormap is wrong even if the player spawns in the alternate colormap area
- fixes on re-init, but only if you are in the alternate colormap area
- if you reload the map it keeps state (fixed or not fixed)
- if you switch maps and return, it is wrong again
- the default colormap area is always correct regardless of the conditions

Maybe the problem is in the level load precache stuff?

**Comment by kraflab** [comment]
Fixed by https://github.com/kraflab/dsda-doom/pull/362
