### ISSUE TITLE
Textures between HI_START/HI_END aren't used in Indexed OpenGL render mode

### ISSUE THREAD

**Issue by anfractu0us** [kraflab/dsda-doom#209]
Not entirely sure if this is by design/due to limitations, but I noticed when testing that while glboom/shaders render modes textures present between HI_START/HI_END are substituted in (at least with an appropriate GLDEFS present - did not test without,) they are not with Indexed selected. I apologize if this is an intentional choice/limitation!

**Comment by kraflab** [comment]
This is unfortunately a limitation of the indexed mode.
