### ISSUE TITLE
Opengl flashing flats

### ISSUE THREAD

**Issue by kraflab** [kraflab/dsda-doom#210]
See clip from decino's stream: https://youtube.com/clip/UgkxzIqFKGXuLYc47dvTMK3rPIWMD1xMSAWp

Basically, some flats are not being drawn randomly, or otherwise getting replaced with the background (this is only my interpretation).

You can see it in the ceiling bars in this screenshot, but it flashes across both ceilings and floors at random.

![flashing_flats](https://user-images.githubusercontent.com/25529060/218309573-0793b7ca-296d-4df1-80b5-6d776b83b558.PNG)

There have been other issues in opengl related to parts of the scene not being drawn and the background or a previous scene popping in randomly. I imagine they're all related to one another.

**Comment by kraflab** [comment]
@JadingTsunami any chance you have an idea of what would cause something like this to happen?

**Comment by JadingTsunami** [comment]
> @JadingTsunami any chance you have an idea of what would cause something like this to happen?

Wow, that's very strange. We can see the architecture behind many of the skipped calls which suggests those flat draw calls simply didn't happen (though I would have expected to see sky texture there in some cases and not solid colors, which is also strange). The skipped draws are also not limited to a single texture or plane, and don't require movement to change.

I can't reproduce this issue locally, but that isn't too surprising given it seems to have started happening 9 hours into this run with multiple save/load cycles and other activity which may have contributed to it.

If it can be reproduced, whether the issue persists after changing resolutions and a switch to and from the software renderer would be interesting data points to gather.

EDIT: Oh, if any changes were made to face culling in the GL renderer in dsda compared to older PrBoom, that might be a place to look.

**Comment by kraflab** [comment]
The issue went away for decino after updating his AMD drivers. I'll close this one for now, but we may see it again.
