### ISSUE TITLE
[Hilarious Heretic Bug] You can jump in midair, at least with this save game.

### ISSUE THREAD

**Issue by yum13241** [kraflab/dsda-doom#218]
Expected behavior: I can't cheese the game.
Actual behavior: I can effortlessly beat the game.

How to reproduce:

1. Download the attached save game.
2. Launch `dsda-doom` with `heretic.wad`. I did NOT use the `-heretic` switch.
3. Jump on ground, then hold jump and jump off. Keep moving. You can reach places easily.

Note: There is very little delay when jumping in Heretic, but Doom uses the GZDoom/Hexen jump. Can you port that to Doom? I don't like waiting an eternity to jump.

[The save  game. Rename `.txt` to `.dsg`.](https://github.com/kraflab/dsda-doom/files/10822218/dsda-doom-savegame0.txt)

**Comment by kraflab** [comment]
Jumping is cheating and not intended in heretic, so of course it cheeses the game.

**Comment by yum13241** [comment]
True, but jumping infinitely in HeXen is cheese. Jumping in HeXen once isn't.

> Jump on ground, then hold jump and jump off. Keep moving. You can reach places easily.
What I meant was that it's possible to jump in midair.


Some times I jump around just to jump, I don't want to accidentally sequence break.
