### ISSUE TITLE
[Heretic Bug] The aspect ratio is wrong on the extended HUD.

### ISSUE THREAD

**Issue by yum13241** [kraflab/dsda-doom#219]
Expected behavior: The Tome Of Power doesn't look like garbage.
Actual behavior: It does.

How to reproduce.

1. Launch Heretic.
2. Set the extended HUD scale to 4 for easier readability.
3. Get a ToP.
4. Select it, BUT DO NOT USE IT!
5. Do the same on the SBar (they aren't in sync)
6. The ToP looks fine on the SBar. but looks squished on the extended HUD.

**Comment by kraflab** [comment]
This is just how the extended hud is. Independent xy scaling for it will be implemented in the future but this isn't a bug.
