### ISSUE TITLE
Rendering error on first frame (pre-melt) in opengl

### ISSUE THREAD

**Issue by kraflab** [kraflab/dsda-doom#220]
Occasionally (not always but not super rare either), opengl has rendering errors on the pre-melt frame. The problem is frozen in place as the background during the melt, but is resolved as soon as the map starts. This happens both on restarts and during continuous play.

![opengl-melt](https://user-images.githubusercontent.com/25529060/221205064-8af5491f-4c29-4b57-a2ce-31d0acc7d78f.jpg)

**Comment by kraflab** [comment]
@JadingTsunami another one of these, maybe you have an idea 😄 
I don't know if it's a symptom of the same problem that affected decino, but this one is specifically about the render behind the melt effect.

**Comment by JadingTsunami** [comment]
Hmm, unfortunately I've never seen this one. What hardware is in use? A long shot, but any chance it's known whether it's limited to a particular hardware type?

**Comment by JadingTsunami** [comment]
Ha, never mind. I see it. I'll fix this in a bit.

**Comment by kraflab** [comment]
Fixed by https://github.com/kraflab/dsda-doom/pull/224
