### ISSUE TITLE
Case-insensitive IWADs

### ISSUE THREAD

**Issue by pizzapim** [kraflab/dsda-doom#232]
I copied my IWADs from the GOG version of Ultimate DOOM but dsda-doom does not detect these files. The problem is that the files are in all caps  (`DOOM.WAD` etc.)  and I think dsda-doom should support these too. I think the original IWADs were in all all caps as well. 

If you agree, I would like to try and program this :)

**Comment by kraflab** [comment]
These files are usually in all caps so that's not the problem. It's more likely that the files aren't in the right place. Where are they and how are you launching it?

**Comment by pizzapim** [comment]
I symlinked them to my home directory as you can see below. If I change the file name to lower-case it works. I compiled it from source just now on the latest PopOS.
```
pim@pop-os:~/Documents/wads$ ls -l /usr/local/share/games/doom
lrwxrwxrwx 1 root root 24 Feb 26 23:38 /usr/local/share/games/doom -> /home/pim/Documents/wads
pim@pop-os:~/Documents/wads$ ls
DOOM.WAD  dsda-doom.wad
pim@pop-os:~/Documents/wads$ dsda-doom 
dsda-doom v0.25.6 (https://github.com/kraflab/dsda-doom/)
IdentifyVersion: IWAD not found

pim@pop-os:~/Documents/wads$ mv DOOM.WAD doom.wad
pim@pop-os:~/Documents/wads$ dsda-doom 
dsda-doom v0.25.6 (https://github.com/kraflab/dsda-doom/)
dsda-doom is released under the GNU General Public license v2.0.
You are welcome to redistribute it under certain conditions.
It comes with ABSOLUTELY NO WARRANTY. See the file COPYING for details.

Playing: The Ultimate DOOM
 adding doom.wad
 adding dsda-doom.wad
```

**Comment by kraflab** [comment]
Oh Linux, it has case sensitive paths, that's why it fails there. Just use -iwad to pick the wad. Automatically finding one iwad isn't a particularly useful feature. If anything I'd sooner delete it than make it case insensitive.

**Comment by kraflab** [comment]
Maybe after the file handling refactor is done I'll just set this up in the core file opening code.

**Comment by pizzapim** [comment]
Fair enough, thanks.
