### ISSUE TITLE
Rendering problem in E5M4 Sigil

### ISSUE THREAD

**Issue by pizzapim** [kraflab/dsda-doom#242]
I noticed the following rendering in E5M4 of Sigil, where the sprites are drawn in front of the walls. Is it a dsda-doom problem?

![doom01](https://user-images.githubusercontent.com/23135512/222545685-c843589b-2e18-46e2-8eef-ec0042df102b.png)

**Comment by El-Juancho** [comment]
Same spot in the original ms-dos doom exe, this is vanilla behavior. The sprites look alright in openGL mode

![image](https://user-images.githubusercontent.com/70743149/223424260-f6a52476-140e-45cc-978b-e8455603b024.png)
