### ISSUE TITLE
opengl broken flat rendering on level restart

### ISSUE THREAD

**Issue by kraflab** [kraflab/dsda-doom#245]
From KD (I also reproduced it myself):

- opengl
- opengl light mode: "glboom" or "shaders"
- minimap on
- automap -> things appearance: "classic" or "scaled"
- use in-game restart to trigger it
- works pretty consistently in doom 2 map01 once it starts, if it's not there from the beginning go to a different map and then start a new game

The attached config is confirmed to reproduce this issue. The restart key is HOME.

It's somehow related to the minimap being rendered. It doesn't seem to happen if it's off. It also happens if the minimap is in overlay mode - but it does not happen if you have the regular automap up in overlay mode. The overlay map is closed when you restart, whereas the minimap stays up - this may be the distinction. Also, if you keep inputting the restart key during the melt (i.e., you chain from melt to melt), the error will only appear once.

![flat_issue](https://user-images.githubusercontent.com/25529060/222926691-67dc9da2-eeb6-481e-b5ce-9ec21b5d6632.png)

Config:
[flats_opengl_ingame_restart_bug.zip](https://github.com/kraflab/dsda-doom/files/10889599/flats_opengl_ingame_restart_bug.zip)

**Comment by kraflab** [comment]
@JadingTsunami since you just fixed a melt-related issue, do you happen to know what would cause something like this? 😅 
Interestingly, the ceiling flats are totally fine, and it's only the first room's flats that are messed up, as the hallway is totally fine.

**Comment by andrey-budko** [comment]
Time to remove "glboom" and "shaders" modes?

They made some sense before you forced GL_NEAREST.

**Comment by kraflab** [comment]
The only thing holding me back after all the indexed mode fixes is that high res textures aren't supported in indexed mode. I think if that gets sorted out the other modes could indeed be removed.

**Comment by JadingTsunami** [comment]
How's that minimap being rendered? Is the area with the chainsaw the same broken texture?

My guess is there's a potential for conflicting instructions as I don't think the non-overlay map was ever built to render atop the live game. But, I would need to look at it more, and I am not familiar with the minimap feature.

**Comment by andrey-budko** [comment]
probably missed gld_ResetLastTexture()

can you reproduce after removing `last_glTexID = gltexture->texid_p;` lines in gl_texture.c?

**Comment by kraflab** [comment]
Thanks! Fixed by https://github.com/kraflab/dsda-doom/commit/b717223303e6f336acf74b27b30ca22fcd5fb65f

> How's that minimap being rendered?

The automap code is actually surprisingly flexible and you can control where it gets drawn with the existing variables, so I just added an option to draw it from the hud rendering code (as opposed to replacing the player view).
