### ISSUE TITLE
[Dev] Turn on more warnings, make them errors

### ISSUE THREAD

**Issue by bkoropoff** [kraflab/dsda-doom#249]
I've been bitten multiple times by bugs in my code that would have been caught early by `-Wall -Werror`.  It's probably good hygiene to turn this on.

**Comment by kraflab** [comment]
How are you compiling the code? It already uses -Wall.

**Comment by bkoropoff** [comment]
Some are turned off, e.g:

`-Wno-unused -Wno-switch -Wno-sign-compare -Wno-pointer-sign`

There are also a lot of warnings in the existing code that aren't fixed, so new ones get lost in the noise.  Making the code `-Wall -Werror` clean can be a big help.

**Comment by kraflab** [comment]
There are no warnings in gcc on msys2. That's why I asked how you compile it. Basically I have no interest in policing warnings for platforms I don't even build on - not right now anyway. I assume -Werror will make it very painful for people using other platforms.
