### ISSUE TITLE
Inclusion of Original Pitched sounds and Pitch Bend Range.

### ISSUE THREAD

**Issue by ghost** [kraflab/dsda-doom#250]
In Woof, there are two features to toggle on/off variable pitch in sound effects and pitch bend range. Those effects are very pleasing to my ears tbh. Ig it would be cool if this port adds two features to toggle on/off those sound effects and those pitch bend range from Id's Original Code to this port just like how Woof has. Playing Doom will be more fun and will never become a chore, at least for me.

**Comment by yum13241** [comment]
In Heretic it was always on.

**Comment by ghost** [comment]
In Doom ?

**Comment by yum13241** [comment]
It was broken in versions past `1.4` I believe, so most people never heard it. To me pitch shifted sounds just sound wrong.

**Comment by kraflab** [comment]
I do not currently have any plans to change the sound behaviour in this way. I'm aware of the topic and will keep it in mind if that changes in the future.

**Comment by ghost** [comment]
Ok. Fine
