### ISSUE TITLE
aaliens map 24 HOM in software mode

### ISSUE THREAD

**Issue by kraflab** [kraflab/dsda-doom#258]
This issue isn't in 0.25.6 and only occurs in the software renderer. Occurs in the default config.

![doom57](https://user-images.githubusercontent.com/25529060/224853691-d1ffce9f-a46b-4c35-8f40-72c13e280bea.png)

**Comment by kraflab** [comment]
@bkoropoff your changes since 0.25.6 have no impact on the software renderer, right? We did "simplify" some of the branching in r_bsp that could affect it. Maybe there was an oversight there. Or it could be from all the rendering work supporting new udmf stuff. Might just need to git bisect this one.

**Comment by bkoropoff** [comment]
It wasn't supposed to affect software, no, so it would be a refactoring bug or oversight.

**Comment by kraflab** [comment]
It indeed was https://github.com/kraflab/dsda-doom/commit/22157589981f02eee81a9bf1e6f83eaad0935ed7
Every time I make an assumption about something like this it seems to backfire 😂

**Comment by kraflab** [comment]
https://github.com/kraflab/dsda-doom/commit/decb318c482c609d2ba4b8ffe7d48c06f00139ae never trust anything in this code base 🤠

**Comment by bkoropoff** [comment]
Yeah, the whole fake flats thing could stand to be refactored so it's not using "fake" `sector_t`s from outside the `sectors` array.  Pass a struct with just the fields that need to be overridden would be better.
