### ISSUE TITLE
[Bug] You can't attack all the way up or down. The attack winds up somewhere else.

### ISSUE THREAD

**Issue by yum13241** [kraflab/dsda-doom#261]
Expected behavior: I can shoot properly.
Actual behavior: I can't.

How to reproduce:

1. Launch Doom II.
2. Start a new game.
3. Type TNTEM and IDKFA.
4. Shoot the SSG on the ground. You may want to look up slightly.

The attack is off.

Considering you can look down to useless extremes in the software renderer, and the hardware renderer renders normally, this is probably a bug.

**Comment by kraflab** [comment]
You cannot shoot the floor with hitscan attacks. This is a limitation of the engine and not a bug, although it might be unexpected behaviour.

**Comment by yum13241** [comment]
> This is a limitation of the engine and not a bug

Not even 89.9 degrees? Then how does GZDoom do it?

**Comment by kraflab** [comment]
gzdoom is an entirely different game engine. That would be like asking how half life does it. Totally different mechanics in play.

**Comment by yum13241** [comment]
That still leaves 1/2 of my question unanswered. Why is it that the limit is ~=70 degrees? Autoaim?

**Comment by kraflab** [comment]
No clue, I didn't write it :^)
If I had to guess, it's some compromise between having too many situations that will regularly produce anachronistic behaviour and player freedom.

**Comment by yum13241** [comment]
So you're saying spawning `BulletPuff`s on the floor causes things to happen at the wrong time? Weird.

Then again Doom's code is a giant mess. For example, the existence of `A_Hoof`. Why they didn't make a universal sound playing function is beyond me.
