### ISSUE TITLE
UMAPINFO support in Heretic

### ISSUE THREAD

**Issue by rfomin** [kraflab/dsda-doom#271]
A new Heretic PWAD is in the works, which may contain UMAPINFO lump with new episode and level names. Everything works, except for the `intertext` field.

Test UMAPINFO:
```
map E1M8
{
    intertext = "Test"
}
```
The current spec says nothing about Heretic, but it works in GZDoom.

---

Things that don't work (more to be investigated):
- [ ] intertext
- [ ] intermusic

**Comment by kraflab** [comment]
Using umapinfo for heretic or hexen is basically undefined in dsda-doom I guess. I'm not sure I want to start adding fixes piecemeal because there will be demo playback concerns between versions 🤔

**Comment by rfomin** [comment]
> demo playback concerns

As far as I know, there are no Heretic/Hexen PWADs with UMAPINFO. Do you mean it might affect non-UMAPINFO demos?

**Comment by kraflab** [comment]
I mean demos recorded at a point before some fixes and then more demos and then more fixes. That would be my concern. In other words I would need to have a comprehensive look at support. Probably need a test umapinfo that uses every feature to see what is broken or if anything crashes 🤔

**Comment by kraflab** [comment]
I changed the issue title and added a checklist fyi

**Comment by rfomin** [comment]
PWAD with `HEHACKED` and `UMAPINFO`: https://doomuniverse.com/topic/116/heretic-of-myth-relinquished-7-map-demo-episode

**Comment by fabiangreffrath** [comment]
> PWAD with `HEHACKED` and `UMAPINFO`: https://doomuniverse.com/topic/116/heretic-of-myth-relinquished-7-map-demo-episode

Is this the project that this PR is targeted at?
https://github.com/fabiangreffrath/crispy-doom/pull/1030

**Comment by rfomin** [comment]
> Is this the project that this PR is targeted at?

Yes, although `ANIMATED` is not used yet.

**Comment by kraflab** [comment]
There's no hehacked support in dsda-doom either. I kind of decided to not bother with that and just work on dwf21 at some point (d'sparil's worst friend) 😄

**Comment by kraflab** [comment]
I'm going to close this issue for now. I've put in a guard clause to block raven games from consuming umapinfo since the behavior is undefined, even if some pieces of it might work. This is going to depend on what I ultimately want to do with these games in the future.
