### ISSUE TITLE
Consider following XDG base directory specification on Linux

### ISSUE THREAD

**Issue by bkoropoff** [kraflab/dsda-doom#283]
Putting everything in `~/.<appname>` has been considered bad practice on Linux for a while.

https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html

- Configuration files usually go in ~/.config/<appname>
- Cache files (anything it's safe to delete) usually go in ~/.cache/<appname>
- Data files (e.g. saves) usually go in ~/.local/share/<appname>

This keeps the home directory clean, lets backup apps only back up important files, lets the cache directory be cleared to reclaim space, etc.

**Comment by kraflab** [comment]
My main concern about changing anything like this is if it will cause problems for existing users

**Comment by bkoropoff** [comment]
The code should detect an existing `~/.dsda-doom` directory and continue using it for config and save games if it's present.  That's how a lot of other Linux apps migrated to the XDG spec.

**Comment by facespkz** [comment]
I remember submitting a patch for this to PrBoom+, only problem is the logic prioritized the path under home directory rather than the default.

**Comment by ndfsa** [comment]
If I'm not mistaken, PrBoom+ has already implemented this in https://github.com/coelckers/prboom-plus/pull/470

**Comment by kraflab** [comment]
https://github.com/kraflab/dsda-doom/commit/38fc904d32f434a8ead3d8c815753fa13e9cdb70
