### ISSUE TITLE
File parsing can crash on non-x86 platforms

### ISSUE THREAD

**Issue by bkoropoff** [kraflab/dsda-doom#285]
A lot of the file parsing code uses casts from `char*`/`byte*` to structs, `short`, `int`, etc.  This generates a lot clang warnings about pointer alignment.

In a lot of cases this is harmless, as the buffer pointer is guaranteed to be aligned due to program logic.  In others it's not, e.g. 

```c
  lump_info = (const filelump_t*)(buffer + header->infotableofs);
```

If the wad header has an `infotableofs` that is not 4-byte aligned for whatever reason, accessing `lump_info->filepos` will crash on platforms like ARM where unaligned memory access is not allowed.

There are attributes/pragmas that can be used to mark structures as 'packed' so that the compiler generates the necessary code to access unaligned memory safely on platforms that require it.

On the other hand, maybe running dsda-doom on anything but x86 doesn't matter.

**Comment by kraflab** [comment]
To be honest I would rather leave this alone until we reach a time where it must be done.

**Comment by bkoropoff** [comment]
This isn't really fixed, the warning is just turned off :laughing:

**Comment by kraflab** [comment]
I'd like everything in the issues tab to be actionable and intended to be addressed, so in this case I decided to close it, although the problem does still exist as you said :^)
