### ISSUE TITLE
Autoload is case-sensitive on Linux

### ISSUE THREAD

**Issue by bkoropoff** [kraflab/dsda-doom#310]
If you load `SCYTHE.WAD`, autoloads in `scythe.wad/` won't be loaded, etc.  Probably need to do case folding somewhere.

**Comment by orffen** [comment]
Also WAD loading is case-sensitive - see https://github.com/kraflab/dsda-doom/pull/346#issuecomment-1508373549

**Comment by mooreye** [comment]
I think it should stay that way - UNIX filesystems are case-sensitive, meaning that DOOM.WAD and doom.wad can exist in the same dir as 2 completely different files with potentially different contents.

**Comment by jjbarr** [comment]
I would be inclined to agree that the behavior should remain as-is. Case-sensitivity is a property of the filesystem, not a property of DSDA-Doom

**Comment by kraflab** [comment]
I don't have any plan to change this behavior right now, so going to close this issue. May do something about it eventually, but I'm inclined to "trust the filesystem" when it comes to naming and what constitutes a difference.
