### ISSUE TITLE
[GL] Rendering artifact on DOOM2 MAP21

### ISSUE THREAD

**Issue by bkoropoff** [kraflab/dsda-doom#318]
Thanks Sandy

![doom05](https://user-images.githubusercontent.com/2101303/229660839-00f43b29-2311-46db-98ba-4adfebc64148.png)
![doom06](https://user-images.githubusercontent.com/2101303/229660866-bd3bf132-8f1f-456c-9306-8129f4e2a832.png)

**Comment by kraflab** [comment]
@bkoropoff would you mind collecting these kinds of problems into one issue with a checklist that links to comments with the image / description?

**Comment by bkoropoff** [comment]
Moved to https://github.com/kraflab/dsda-doom/issues/338
