### ISSUE TITLE
[Feature request] Make a separate render resolution setting separate from window resolution for windowed mode.

### ISSUE THREAD

**Issue by Vitoria90** [kraflab/dsda-doom#321]
I want to play the game in borderless window mode but be able to make the software render look very low res and crispy.
Also if possible could you add a custom resolution setting that lets you type in your resolution? It would be nice to run the game at 240px height with proper 16:9 aspect ratio.

**Comment by kraflab** [comment]
This is already how it works. Did you not try it?

**Comment by kraflab** [comment]
You may need to turn off exclusive fullscreen if you have that selected, since that will change your screen resolution to match.

**Comment by kraflab** [comment]
It's also already possible to set a custom resolution.

**Comment by kraflab** [comment]
I'd suggest either asking on doom world or on the discord if you're having trouble with the settings. If that leads to no success and it turns out to be a bug, you can file a new issue for that purpose.

**Comment by Vitoria90** [comment]
Exclusive fullscreen is turned off here, and changing the resolution to lower just turns the game into an actual window of that resolution.
