### ISSUE TITLE
[gl] New crash with gl_usevbo=1 gl_skymode=3

### ISSUE THREAD

**Issue by kraflab** [kraflab/dsda-doom#325]
I assume this was introduced when adding the new vbo feature.

Launch with `-assign gl_usevbo=1 gl_skymode=3`

To crash:
1) look at the sky
2) enter idbeholdv

This branch in `RenderDome` is related:
```c
  if (invul_method == INVUL_CM && frame_fixedcolormap == INVERSECOLORMAP)
    vbo = &sky_vbo[1];
  else
    vbo = &sky_vbo[0];
```

If you already have god mode when you look at the sky, it will instead crash when you lose god mode and look at the sky.

**Comment by kraflab** [comment]
@bkoropoff fyi, discovered this while looking into unrelated sky stuff

**Comment by bkoropoff** [comment]
I couldn't reproduce this, but I found something on code inspection that might be the cause

**Comment by andrey-budko** [comment]
probably something like this?
https://pastebin.com/RPLasR0s

> I couldn't reproduce this

gl_lightmode=1

**Comment by kraflab** [comment]
Oops ya, this sky mode isn't in indexed light mode.

**Comment by andrey-budko** [comment]
> this sky mode isn't in indexed light mode

Why? Any issues with skydome?

**Comment by andrey-budko** [comment]
probably because of the palette change (pain, etc)

**Comment by kraflab** [comment]
Xaser just focused on making it work with 1 mode as a base. I am currently digging into a bunch of sky code though, I'll be looking at that as well

**Comment by kraflab** [comment]
Now the skydome works in indexed mode in master as well - the cap color doesn't update with palette but it's pretty insignificant and I'll fix it separately.

**Comment by andrey-budko** [comment]
Is something wrong with suggested patch to fix the issue? I can pull request, if you want.

**Comment by kraflab** [comment]
Oh sorry, I completely missed that you linked a patch 😄 
Will take a look now

**Comment by kraflab** [comment]
https://github.com/kraflab/dsda-doom/commit/099b3aaa5c1ca3f9c8f814effb0e3ecac0f1a27a thanks!
