### ISSUE TITLE
[GL] `gld_RecalcVertexHeights` code shouldn't malign ATI

### ISSUE THREAD

**Issue by bkoropoff** [kraflab/dsda-doom#334]
This function splits the left/right edges of wall polygons for each adjacent floor/ceiling so that there is an intermediate vertex for each height level, apparently because old ATI cards would have seams or other artifacts otherwise.  If this is not a concern on video cards dsda-doom needs to support, this code can be yanked out for extra performance and cleaner code.

**Comment by andrey-budko** [comment]
I think this code is required, and ATI uscks comment can be removed (it is from gzdoom).

google T-Junction Problem

**Comment by bkoropoff** [comment]
Makes sense
