### ISSUE TITLE
Music volume levels are very low

### ISSUE THREAD

**Issue by thekovic** [kraflab/dsda-doom#366]
I tried multiple soundfonts with Fluidsynth playback in DSDA-Doom and the volume level at the same "Music Volume" settings in the menu is consistently much, much lower than the same soundfont at the same volume in Chocolate Doom.

**Comment by kraflab** [comment]
I suggest asking for help with this kind of configuration problem on the doomworld forums first. If you can't figure it out then feel free to reopen the issue - though even then I would suggest bringing the topic to the discord. This kind of open-ended not-a-bug topic isn't served particularly well as a github issue without something concrete.

**Comment by thekovic** [comment]
Which Discord would that be?

I disagree with calling this a "not-a-bug". I've played DOOM in many source ports over the year and I've never encountered one where music is so quiet as this one. I can barely hear any music even on max volume settings. This is particularly curious as all use Fluidsynth for playback. Perhaps a video recording would demonstrate the issue better?

**Comment by andrey-budko** [comment]
Did you try to change `mus_fluidsynth_gain` in cfg? It's 50 by default, but you can increase it up to 1000
