### ISSUE TITLE
[Feature Request] Transparent classic HUD

### ISSUE THREAD

**Issue by thekovic** [kraflab/dsda-doom#367]
This is my favorite feature from Crispy Doom (and descendants) that I haven't been able to find in DSDA-Doom. I like to play with the viewport across the entire width of the screen but I'd like to have HUD at the same time. Extended HUD on max screen size is nice but crucial info like health level is too small. The classic DOOM HUD but with the background and the Doomguy face not rendered is the best solution I have seen yet.

**Comment by kraflab** [comment]
You can already configure large text / patches for things like health in the full screen hud. I make iterative changes to the hud possibilities so I will probably introduce more stuff in the future, but I will close this issue for now.

**Comment by thekovic** [comment]
> You can already configure large text / patches for things like health in the full screen hud.

How can I do that? I'm more than willing to configure stuff but like I said, I haven't been able to find anything satisfactory. If it turns out to indeed be possible, then this is a documentation issue imo.
