### ISSUE TITLE
[Feature Request] Option to Show Map Name On-Screen Upon Map Start

### ISSUE THREAD

**Issue by batbrain55** [kraflab/dsda-doom#369]
Add an option show the name of a map you start on screen for a few seconds when you start it, to save you having to look at the automap. It would be cool if this message showed up in the bottom-left or bottom-right corner of the screen (above the classic HUD if it is enabled), kind of like a music video. That way there'd be less potential problems with the text overlapping or overriding messages that are displayed instantly when some maps start.

**Comment by kraflab** [comment]
It's an interesting idea, but all four corners of the display already have text :^)

There are also already map-start messages as you mentioned. I've been meaning to rewrite how messages work generally, so this may be a good excuse.

**Comment by batbrain55** [comment]
"all four corners of the display already have text :^)"

Yes, but because this text would only show for a few seconds or so, you could have it replace the text it overlaps with for this time, or slightly shift where it is on the screen so nothing's overlapping, and have it not be too intrusive.

Or, instead (or as another display option), the level name could be shown in the dead center of the screen in the difficulty select font, kind of how it's done in DUSK.

Here's a visualisation of the options this setting could have. Some of this might just end up as useless option bloat (I've marked the ones I'm unsure about as "you never know", but ultimately implementation is up to you.

Show map name on level start: No [Default]/Yes [when set to no, all other options are greyed out/hidden]
Map name display time: Slider, 1-20 seconds or so, about 3 seconds by default
Show level number: No/Yes [not sure which should be default, because this would be helpful with the screen corner options but unhelpful with the big text option]
Map name display location: Top/bottom left/right corner, Top center [where the 'secret found' text is displayed], center (small text) [you never know], center (big text)
Handle Overlapping Text: Hide until map name fades/Move until map name fades/Allow overlap (not recommended) [you never know]

**Comment by kraflab** [comment]
I don't need any help on the solution side 😉

**Comment by kraflab** [comment]
https://github.com/kraflab/dsda-doom/commit/09cc30a89ab84edd16ef084bd6cb4a0d062a0632
