### ISSUE TITLE
[Feature Request] Item Get/Secret Found font for Extended HUD on Status Bar

### ISSUE THREAD

**Issue by batbrain55** [kraflab/dsda-doom#370]
Currently, when using the extended HUD on the status bar to show time, kills, items and secrets, it shows it in a small font that I find kind of hard to read. (Note that I don't use the full extended HUD, only the partial one with the status bar.) I would prefer if it was shown in the item get/secret found font, except maybe altered to be monospaced so it doesn't 'jitter' from constantly resizing itself due to different letters having different widths. I would be fine with it staying unchanged in all aspects other than the font, although it'd also be nice to have the option to disable the time display.

Keep up the good work, and thanks for hearing me out.

**Comment by kraflab** [comment]
You can change what components show up on the hud yourself, check the docs area and ask on dw/discord if you need help. If you want to use a different font for a component, your best bet would be to just replace the font patches directly. I will probably introduce font configuration in the future, but not any time soon, so I will close this issue for the time being.
