### ISSUE TITLE
[GL] skymode 2 behaves inconsistently with different FOVs

### ISSUE THREAD

**Issue by bkoropoff** [kraflab/dsda-doom#373]
GL:

![doom00](https://github.com/kraflab/dsda-doom/assets/2101303/23c72de7-d397-441e-8846-9481eb14f89b)

Software:

![doom01](https://github.com/kraflab/dsda-doom/assets/2101303/dfdd9507-15f3-4dd4-b92c-faf7b5f01176)

**Comment by kraflab** [comment]
This is intentional. It's to give more room for looking up before regressing to the fade out.

**Comment by bkoropoff** [comment]
Shouldn't it only do it with mouselook on, then?

**Comment by bkoropoff** [comment]
Part of the problem is that behavior is inconsistent between FOVs.

FOV 90:

![doom00](https://github.com/kraflab/dsda-doom/assets/2101303/6a1497ff-1681-45cf-a5f1-a7475018a51b)

FOV 110:

![doom01](https://github.com/kraflab/dsda-doom/assets/2101303/45fb1053-b20f-4996-a74f-46498436507b)

**Comment by bkoropoff** [comment]
At FOV 90, it *does* switch behavior when toggling mouselook.  This is probably because behavior is specifically keyed on `mlook_or_fov`, so at `gl_render_fov != 90`, it's as if mouselook is always on.

**Comment by bkoropoff** [comment]
Heretic is also inconsistent with FOV:

## FOV 90

![doom00](https://github.com/kraflab/dsda-doom/assets/2101303/9cd34ac3-9756-4cff-9ea3-d20b31a686e5)

## FOV 110

![doom01](https://github.com/kraflab/dsda-doom/assets/2101303/704d4293-aeab-4e6c-bcf6-301a63470ff4)
