### ISSUE TITLE
Issue with 'cmake' command. Unable to install on linux (Kubuntu 22.04 LTS).

### ISSUE THREAD

**Issue by aditya-347** [kraflab/dsda-doom#407]
I followed the installation instructions (For Linux, Kubuntu 22.04 LTS)  as given in the "INSTALL" file.
When I try to run 'cmake .. -DCMAKE_BUILD_TYPE=Release', I get the following error:

-- The C compiler identification is GNU 11.3.0
-- The CXX compiler identification is GNU 11.3.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for stricmp
-- Looking for stricmp - not found
-- Looking for strnicmp
-- Looking for strnicmp - not found
-- Looking for getopt
-- Looking for getopt - found
-- Looking for mmap
-- Looking for mmap - found
-- Looking for CreateFileMapping
-- Looking for CreateFileMapping - not found
-- Looking for strsignal
-- Looking for strsignal - found
-- Looking for mkstemp
-- Looking for mkstemp - found
-- Looking for sys/wait.h
-- Looking for sys/wait.h - found
-- Looking for unistd.h
-- Looking for unistd.h - found
-- Looking for asm/byteorder.h
-- Looking for asm/byteorder.h - found
-- Looking for dirent.h
-- Looking for dirent.h - found
-- Performing Test HAVE_WALL
-- Performing Test HAVE_WALL - Success
-- Performing Test HAVE_WWRITE_STRINGS
-- Performing Test HAVE_WWRITE_STRINGS - Success
-- Performing Test HAVE_WUNDEF
-- Performing Test HAVE_WUNDEF - Success
-- Performing Test HAVE_WTYPE_LIMITS
-- Performing Test HAVE_WTYPE_LIMITS - Success
-- Performing Test HAVE_WCAST_QUAL
-- Performing Test HAVE_WCAST_QUAL - Success
-- Performing Test HAVE_WPOINTER_ARITH
-- Performing Test HAVE_WPOINTER_ARITH - Success
-- Performing Test HAVE_WNO_UNUSED_FUNCTION
-- Performing Test HAVE_WNO_UNUSED_FU
[CMakeError.log](https://github.com/kraflab/dsda-doom/files/11781756/CMakeError.log)
[CMakeOutput.log](https://github.com/kraflab/dsda-doom/files/11781757/CMakeOutput.log)
NCTION - Success
-- Performing Test HAVE_WNO_SWITCH
-- Performing Test HAVE_WNO_SWITCH - Success
-- Performing Test HAVE_WNO_SIGN_COMPARE
-- Performing Test HAVE_WNO_SIGN_COMPARE - Success
-- Performing Test HAVE_WNO_FORMAT_TRUNCATION
-- Performing Test HAVE_WNO_FORMAT_TRUNCATION - Success
-- Performing Test HAVE_WNO_MISSING_FIELD_INITIALIZERS
-- Performing Test HAVE_WNO_MISSING_FIELD_INITIALIZERS - Success
-- Performing Test HAVE_WABSOLUTE_VALUE
-- Performing Test HAVE_WABSOLUTE_VALUE - Success
-- Performing Test HAVE_WNO_POINTER_SIGN
-- Performing Test HAVE_WNO_POINTER_SIGN - Success
-- Performing Test HAVE_WDECLARATION_AFTER_STATEMENT
-- Performing Test HAVE_WDECLARATION_AFTER_STATEMENT - Success
-- Performing Test HAVE_WBAD_FUNCTION_CAST
-- Performing Test HAVE_WBAD_FUNCTION_CAST - Success
-- Performing Test HAVE_FFAST_MATH
-- Performing Test HAVE_FFAST_MATH - Success
-- Performing Test HAVE_FP_FAST
-- Performing Test HAVE_FP_FAST - Failed
-- Found OpenGL: /usr/lib/x86_64-linux-gnu/libOpenGL.so (Required is at least version "2.0")  
CMake Error at /usr/lib/x86_64-linux-gnu/cmake/libzip/libzip-targets.cmake:93 (message):
  The imported target "libzip::zipcmp" references the file

     "/usr/bin/zipcmp"

  but this file does not exist.  Possible reasons include:

  * The file was deleted, renamed, or moved to another location.

  * An install or uninstall procedure did not complete successfully.

  * The installation package was faulty and contained

     "/usr/lib/x86_64-linux-gnu/cmake/libzip/libzip-targets.cmake"

  but not all the files it references.

Call Stack (most recent call first):
  /usr/lib/x86_64-linux-gnu/cmake/libzip/libzip-config.cmake:42 (include)
  CMakeLists.txt:113 (find_package)

-- Configuring incomplete, errors occurred!
See also "/home/{user}/Downloads/Compressed/dsda-doom/prboom2/build/CMakeFiles/CMakeOutput.log".
See also "/home/{user}/Downloads/Compressed/dsda-doom/prboom2/build/CMakeFiles/CMakeError.log".

**Comment by fabiangreffrath** [comment]
> The imported target "libzip::zipcmp" references the file
> 
> ```
>  "/usr/bin/zipcmp"
> ```
> 
> but this file does not exist

How explicit do you need it?

**Comment by aditya-347** [comment]
> > The imported target "libzip::zipcmp" references the file
> > ```
> >  "/usr/bin/zipcmp"
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > but this file does not exist
> 
> How explicit do you need it?

Sorry! I'm new to linux & totally unfamiliar with tools like cmake. I tried google search, but, unfortunately, could not find any solution. What am I supposed to do here?

**Comment by fabiangreffrath** [comment]
Install the `zipcmp` package. 😉

**Comment by aditya-347** [comment]
> Install the `zipcmp` package. wink

@fabiangreffrath I installed the packages `zipcmp`, `zipmerge` & `ziptool` and was able to get it installed properly. Thank you for your help.

https://www.mail-archive.com/debian-bugs-dist@lists.debian.org/msg1771040.html
