### ISSUE TITLE
Mobj health tracker interacts poorly with build mode

### ISSUE THREAD

**Issue by perryprog** [kraflab/dsda-doom#411]
I'm running into an issue where in build mode, tracking the health of a mobj will give essentially garbage values. For a zombieman, it'll sometimes say twenty, quite often 1000, othertimes 60, and very rarely it'll show 1065353216 (0x3F800000, or 1.0 as floating point, which is neat). Anyway, it's probably some memory issue. Here's my steps to reproduce:

1. Load Scythe Map01 (or any map).
2. Track the two zombies out front with `t.am 39` and `t.am 40`.
3. Observe that their health is tracked fine when shooting them.
4. Enter build mode.
5. Tweak the current tic by turning, shooting and unshooting, or anything else a few times and watch the health change.

**Comment by kraflab** [comment]
Thanks for the report. This is a known issue. There are lots of issues with build mode that are still getting refined. I track this stuff on discord so as not to bloat the issue tracker here, which I lean on keeping limited to bigger topics that may warrant discussion, preservation, and / or things I need support on, so as to avoid noise.

**Comment by perryprog** [comment]
Ah, got it. I wasn't sure if that was the case but I don't use Discord myself.
