### ISSUE TITLE
STARMS does not register SSG pickup when SSG is picked up before shotgun

### ISSUE THREAD

**Issue by DreadWanderer** [kraflab/dsda-doom#414]
STARMS does not register SSG pickup when SSG is picked up before shotgun

Repro steps:

1.  Start DSDA-Doom 0.26.2
2.  Warp to a map where you pick up the SSG before the shotgun (for example, MAP05 of Doom 2)
3. Notice that the number 3 on STARMS remains greyed out despite picking up the SSG

Additional information:

- Tested on Windows 10 x64;
- Tested on multiple complevels (2, 9, 11, 21);
- Tested both with vanilla status bar and wads that use custom status bars;
- Please see video link below for clarification;

https://github.com/kraflab/dsda-doom/assets/140856912/00c6fcc4-f49f-4f0d-bdf5-972fd39105b0

**Comment by kraflab** [comment]
This is how it is in doom, it's not a bug.

**Comment by DreadWanderer** [comment]
> This is how it is in doom, it's not a bug.

Ah didn't know that, thank you for the info. My apologies for wasting your time!
