### ISSUE TITLE
Getting visual glitches/crashes after playing for around 30 mins, every time

### ISSUE THREAD

**Issue by jadekitt** [kraflab/dsda-doom#415]
When it happens, in OpenGL mode, the screen goes crazy with visual glitches. In Software mode, I get a crash with an error instead: "Please report the following information: signal 11 (0x0203)". I have to restart the game to fix it. It happens every time I play. Also, it happens regardless if I pause the game or not.

My specs: Ryzen 2600, GTX 1070Ti, 16 GB RAM, Windows 10.

I've checked for memory leak or temperature, there is no problem there. And I do not have such issues in any other game.

Edit: Forgot to mention that, if I do something else for 30 mins and come back (in OpenGL mode), the bug fixes itself somehow lol. Not sure if helpful or not.

**Comment by kraflab** [comment]
0x0203 means that it is crashing inside `R_RenderPlayerView` in this section:
```c
  if (V_IsSoftwareMode()) {
    DSDA_ADD_CONTEXT(sf_draw_masked);
    R_DrawMasked ();
    R_ResetColumnBuffer();
    DSDA_REMOVE_CONTEXT(sf_draw_masked);
  }
```

**Comment by kraflab** [comment]
This issue has happened to other people but only certain people have it. I suspect it is a bug that is only exposed by certain hardware, but I don't really know.

**Comment by ClassicSSGEnjoyer** [comment]
> This issue has happened to other people but only certain people have it. I suspect it is a bug that is only exposed by certain hardware, but I don't really know.

even I had the experienced the same bug.

My processor is : Intel R Pentium R CPU G3240 @ 3.10 ghz

**Comment by kraflab** [comment]
Jadekitt's config: [config.zip](https://github.com/kraflab/dsda-doom/files/12231380/config.zip)

**Comment by ClassicSSGEnjoyer** [comment]
but i experinced this bug only once when i started viddumping.

**Comment by jadekitt** [comment]
Forgot to mention that, if I do something else for 30 mins and come back (in OpenGL mode), the bug fixes itself somehow lol. Not sure if helpful or not.

**Comment by fabiangreffrath** [comment]
30 mins corresponds to ~63000 gametics. Maybe a `short` overflow somewhere?

**Comment by kraflab** [comment]
That's a great catch, sounds very promising 🤔

**Comment by kraflab** [comment]
Jadekitt tested out running at a higher gamespeed and the crash timing is not based on the in-game timer, so that appears to be a coincidence.

**Comment by kraflab** [comment]
Jadekitt tested running the game with the vanilla capped framerate and the bug doesn't happen (at least at the usual time). So either the bug has to do with how many frames have been rendered, or the bug is exposed by the interpolated rendering.

**Comment by kraflab** [comment]
Turning uncapped framerate on instantly triggers the bug, and turning it off removes the bug, so this isn't about how many frames have been rendered but about the interpolation itself. Guessing there is some issue in the timer code.

**Comment by kraflab** [comment]
~36 minutes in microseconds would overflow a signed int

**Comment by kraflab** [comment]
`In ISO C, time_t can be either an integer or a floating-point type, and the meaning of time_t values is not specified` ok this looks pretty likely as the suspect, since there's no casting going on here:
```c
  return (now.tv_nsec - dsda_time[timer].tv_nsec) / 1000 +
         (now.tv_sec - dsda_time[timer].tv_sec) * 1000000;
```
The question then is what's the best way to do this 🤔

**Comment by kraflab** [comment]
Going to test just this
```c
  return (unsigned long long) (
           (signed long long) (now.tv_nsec - dsda_time[timer].tv_nsec) / 1000 +
           (signed long long) (now.tv_sec - dsda_time[timer].tv_sec) * 1000000
         );
```

**Comment by kraflab** [comment]
https://github.com/kraflab/dsda-doom/commit/71b59e3bf1efd95b4274ff08844188ffc1b94b66
Fixed!
