### ISSUE TITLE
Problems with new large fullscreen HUD

### ISSUE THREAD

**Issue by d-bind** [kraflab/dsda-doom#416]
Some things I ran into while trying to restore the old minimalist status bar.

[Custom HUD](https://github.com/kraflab/dsda-doom/files/12262611/hud.zip), [in-game](https://github.com/kraflab/dsda-doom/assets/104466974/80516bf0-d8cc-46c2-85db-bd33dd2a0f7a), [0.24.3 for comparison](https://github.com/kraflab/dsda-doom/assets/104466974/45efbb31-4fb5-4556-a3a5-18b7dd263506)

1. Armor and health are always colorized (don't respect "sts_always_red")
2. Ammo is never colorized (doesn't respect "hud_ammo_red"/"hud_ammo_yellow")
3. Armor and health counters start misaligned by 3 pixels, and [slide further apart](https://github.com/kraflab/dsda-doom/assets/104466974/655af74f-7826-4d44-930b-068cb520e13e) as you get damaged. But this also depends on their icon sizes, which could vary [depending on the wad being played](https://github.com/kraflab/dsda-doom/assets/104466974/6e9359ed-1bf8-497f-958c-2a123fae751f).
4. The newly-enforced palette under OpenGL doesn't always work well [with colorized numbers](https://github.com/kraflab/dsda-doom/assets/104466974/6e9359ed-1bf8-497f-958c-2a123fae751f). There doesn't seem to be a way to turn 8-bit mode off. In 0.24.3 this worked fine [even under software mode](https://github.com/kraflab/dsda-doom/assets/104466974/971c4e9b-1ade-4118-989d-18c56e15431d).
5. Everything is scaled to some arbitrary non-integer number, leading to differently-sized "pixels" (4x4, 5x5). I couldn't find any setting to change the scaling manually. In 0.24.3 I couldn't find a setting either, but at least it used an integer scale.
6. The digit '1' is drawn with an extra 1px offset to the left. But only for health, not for ammo. Or something like that? In older DSDA versions it had a 1px offset to the right instead, when compared to the full status bar.
7. Feature suggestion: ammo type icon as a separate component.
8. Feature suggestion: doomguy's face as a separate component.

**Comment by kraflab** [comment]
Please follow the instructions for opening (or not opening) issues in this repo.

**Comment by d-bind** [comment]
Not seeing any instructions here, in readme, in discord FAQs or in discord pinned messages.
If you meant "register for a social network, search through stuff not indexed by search engines, and then spend a day talking this through" then thanks but no thanks.
