### ISSUE TITLE
Slightly Optimize OpenGL renderer for low-end hardware.

### ISSUE THREAD

**Issue by ghost** [kraflab/dsda-doom#417]
Dear DSDA-Doom developers,

I hope you're doing well. I would like to address a minor performance issue related to the OpenGL renderer in DSDA-Doom on my low-end hardware setup.

My system is equipped with an Intel R Pentium G3240 CPU running at 3.10 GHz and an OpenGL version 4.3. In general, DSDA runs smoothly on my PC, maintaining a consistent framerate of 60 frames per second (FPS). However, there are occasional instances where the framerate drops to around 50 or even 45 FPS for a brief moment before returning to 60 FPS.

These framerate fluctuations occur sporadically during gameplay, regardless of the complexity of the scene or the number of entities present. It's worth noting that I play the game at a resolution of 1280x720.

While the drop in framerate doesn't severely affect my overall experience, it does disrupt the fluidity and responsiveness of the game. 

I wanted to bring this matter to your attention in the hope that you could investigate and potentially optimize the OpenGL renderer for better stability on low-end hardware configurations. 

Thank you.

**Comment by kraflab** [comment]
We don't track general open-ended topics like this on github.
