### ISSUE TITLE
Does not play internal demos

### ISSUE THREAD

**Issue by fabiangreffrath** [kraflab/dsda-doom#424]
```
$ dsda-doom -playdemo demo1
dsda-doom v0.26.2 (https://github.com/kraflab/dsda-doom/)
Unable to find required file "demo1"
```

Bleh!

This could be fixed with the following change:

```diff
--- a/prboom2/src/dsda/playback.c
+++ b/prboom2/src/dsda/playback.c
@@ -117,7 +117,7 @@ static void dsda_UpdatePlaybackName(const char* name) {
     Z_Free(playback_filename);
 
   playback_name = Z_Strdup(name);
-  playback_filename = I_RequireFile(playback_name, ".lmp");
+  playback_filename = I_FindFile(playback_name, ".lmp");
 }
 
 const char* dsda_ParsePlaybackOptions(void) {
```

**Comment by kraflab** [comment]
How does it open it with that patch 🤔 
I mean I see that it does, but where in the code does it actually search for an internal lump instead of a file 🤔

**Comment by kraflab** [comment]
Ah I see, if it doesn't have the file in LoadDemo it goes for a lump instead.

**Comment by kraflab** [comment]
I would probably instead create a new command like `-playreel 1`

**Comment by fabiangreffrath** [comment]
That patch was merely an ad hoc solution to get demo playback working. It doesn't bail out with e.g. `-playdemo demo9`. I guess you'll need something like `I_RequireFileOrLump()` or similar.

**Comment by fabiangreffrath** [comment]
> I guess you'll need something like `I_RequireFileOrLump()` or similar.

Would you like a PR for that?

**Comment by kraflab** [comment]
Well, I don't want internal lumps to work for this command line argument, so I wouldn't add such a function. If I would support this feature, it would be via a separate arg. I can add that at some point.

**Comment by fabiangreffrath** [comment]
I'd say that's common sense among source ports that even Chocolate Doom supports, but well, your choice. 🤷

**Comment by kraflab** [comment]
It's not common sense; many of the things other ports all do are not common sense. If you're looking at this objectively, it doesn't make any sense that playing back a file that doesn't exist would fall back on playing a lump of the same name in a different file. People who have found out this is possible generally learn it like it's a trick, not as something obvious that they intuitively knew. Something like `-playreel 1` would make more sense and also solve the problem of the ambiguity of wanting to test an actual file demo1.lmp versus playing back the embedded demo1 lump. Of course, no one will know this command exists either, but when they learn about it it will make sense 😉

**Comment by fabiangreffrath** [comment]
Any progress here? Anything I can help? It's really inconveniet that I cannot play e.g. DEMO4 of a PWAD without dissecting it with deutex before.

**Comment by kraflab** [comment]
Done https://github.com/kraflab/dsda-doom/commit/e6ff1c63c46986c56ae902d691b26f607e0bc97b

**Comment by fabiangreffrath** [comment]
Thank you!
