### ISSUE TITLE
HOM in OpenGL Indexed Renderer (and Not in Software)

### ISSUE THREAD

**Issue by andrikpowell** [kraflab/dsda-doom#427]
So I just recently released a project I've been leading called "Hell Revealations", and for the most part the OpenGL Indexed Render renders everything pretty close to how it should. (still doesn't do midtex bleeds, but that's probably to be expected from an OpenGL renderer).

However in MAP29, I found that a HOM (hall of mirrors) effect only shows up in OpenGL and not software.
I have recorded a video to show how it looks and how the setup of the sectors there are:

https://youtu.be/ZsGNOfXbdcQ

I'm not surprised it doesn't know how to render this. It's sort of based on the invisible door hack used in Hell Revealed MAP01, but it is flat bleeding over multiple sectors instead of just one.

Before you say anything about tweaking how the sectors are put together, there is no way for me to get the same effect and keep that room under the VPO and drawseg limits as it is a Vanilla megawad.

Just thought I'd post this here, cuz other OpenGL ports like GZDoom render it correctly. It'd be nice for this to get fixed at some point.

**Comment by kraflab** [comment]
I've linked this in the page that collects opengl issues, so I'll close this individual one. Unfortunately it's unlikely that many of those issues will be fixed any time soon. If you're concerned about this from the player perspective, you can create a plain text lump called `DSDAPREF` and put the line `prefer_software` in it. Then players will see the message "This wad may have rendering errors in software mode!" when starting it up using the opengl renderer (at least, anyone using more recent versions of the port).
