### ISSUE TITLE
Is it possible to use the standard Doom font with the extended HUD?

### ISSUE THREAD

**Issue by mtslzr** [kraflab/dsda-doom#428]
I've tried looking through the repo, Doomworld, and the Discord and couldn't find if it is possible to use the Doom font instead of the default font for the Extended HUD?

**Comment by kraflab** [comment]
Issues are used to report bugs or track features. Please ask future questions like this directly on discord. The answer is no, there is no way to do that currently.

**Comment by mtslzr** [comment]
Sorry... but since it doesn't exist, this could be considered a feature request, which does fit the listed topics for Issues.
