### ISSUE TITLE
Getting signal 11 (0x0001) crash when trying to enable OpenGL renderer

### ISSUE THREAD

**Issue by AtifArshad1995** [kraflab/dsda-doom#430]
I get this error whenever I try to switch to OpenGL, thus making it impossible to change the renderer. This was not an issue on DSDA 0.26.2

My specs:
Laptop: Dell Inspiron 5570
OS: Windows 10
GPU: AMD Radeon 530 (updated to latest drivers)
CPU: Intel Core i5 8250U
RAM: 4 GB

**Comment by kraflab** [comment]
Have you tried deleting your config file and starting from a fresh config?

**Comment by kraflab** [comment]
Try out 0.27.1, it fixes an opengl crash.

**Comment by AtifArshad1995** [comment]
Just gave 0.27.2 a try and still getting the same crash, even when deleting and using a fresh config.

**Comment by kraflab** [comment]
What happens if you manually edit your config file so `videomode` is `"OpenGL"`? Does it crash on launch? Narrowing down if it's the changing to opengl during runtime that causes the crash or if the renderer will always crash.

**Comment by AtifArshad1995** [comment]
> What happens if you manually edit your config file so `videomode` is `"OpenGL"`? Does it crash on launch? Narrowing down if it's the changing to opengl during runtime that causes the crash or if the renderer will always crash.

Changing it to OpenGL in config makes it crash at launch with same Signal 11 error.

Also, if this helps, I would like to mention that in one of the tries when I switched to OpenGL, I saw the DSDA's loading bar for a split before getting the crash.

**Comment by kraflab** [comment]
I created a new build of 0.26.2. Could you confirm that opengl still works completely fine for you with this build? This is to confirm that the way I'm compiling and packaging builds right now is not to blame.

[dsda-doom-0.26.2.zip](https://github.com/kraflab/dsda-doom/files/13221237/dsda-doom-0.26.2.zip)

**Comment by AtifArshad1995** [comment]
> I created a new build of 0.26.2. Could you confirm that opengl still works completely fine for you with this build? This is to confirm that the way I'm compiling and packaging builds right now is not to blame.
> 
> [dsda-doom-0.26.2.zip](https://github.com/kraflab/dsda-doom/files/13221237/dsda-doom-0.26.2.zip)

I just tried this out and it is working without issues.

No idea why 0.27 is crashing.

**Comment by kraflab** [comment]
Do you have access to discord? If you're willing to continue trying builds, I think we can narrow this down, but it will probably require a lot of back and forth checking things.

**Comment by VanBog335** [comment]
> Do you have access to discord?

yes: vanbog

**Comment by AtifArshad1995** [comment]
> Do you have access to discord? If you're willing to continue trying builds, I think we can narrow this down, but it will probably require a lot of back and forth checking things.

Yes. I am ReaperAA. Just joined the Hell on Earth discord server.

**Comment by kraflab** [comment]
Fixed here: https://github.com/kraflab/dsda-doom/commit/a6468fe45a072d70659ef271bde60258f83e4855
