### ISSUE TITLE
Wipe screen triggers twice when automatically loading a saved game upon death

### ISSUE THREAD

**Issue by DreadWanderer** [kraflab/dsda-doom#432]
Repro steps:

1. Load a map of your choice

2. Save your game

3. Get the player killed with the method of your choice

4. Notice that the wipe screen triggers twice when automatically loading a saved game upon death

Notes:

- Running DSDA-Doom 0.27.0 on Windows 10 x64;

- Loading a saved game manually only triggers the wipe screen once;

- Videos attached for clarification;

https://github.com/kraflab/dsda-doom/assets/140856912/ebb45c79-1e0d-4def-ae11-b290d07a24f4

https://github.com/kraflab/dsda-doom/assets/140856912/4c3b35c3-e359-4bf4-a23e-ec2a867b4362

**Comment by kraflab** [comment]
Confirmed on my end as well.

**Comment by kraflab** [comment]
Fixed here: https://github.com/kraflab/dsda-doom/commit/d2993e56a2de6036fe88f846222b3bf40329299c
