### ISSUE TITLE
opengl bug

### ISSUE THREAD

**Issue by VanBog335** [kraflab/dsda-doom#433]
this is 0.27.2, opengl broken for some reason. it worked fine on 0.26.2

laptop specs:
OS: Windows 10
CPU: AMD Athlon 300U
RAM: 8 GB

https://github.com/kraflab/dsda-doom/assets/114172637/841a7c0c-f509-49ed-9a41-b18f7cf536b7

**Comment by kraflab** [comment]
Although it isn't crashing for you, I think it's probably the same core problem, so follow this one: https://github.com/kraflab/dsda-doom/issues/430
