### ISSUE TITLE
OPL skips notes in MIDIs

### ISSUE THREAD

**Issue by unithecutie** [kraflab/dsda-doom#435]
An example of this is "Soviet Porno" from Freedoom. (DSDA-Doom)

https://github.com/kraflab/dsda-doom/assets/139153158/dcffb1b5-7abf-4769-a86c-58895ef9781a

versus how it's supposed to sound with OPL. (Chocolate Doom)

https://github.com/kraflab/dsda-doom/assets/139153158/b76ec5c3-19ad-485e-a2a6-d9e1856a0114

If I find more MIDIs like this, I will upload more clips.

**Comment by rfomin** [comment]
This track doesn't sound like "Soviet Porn", I think it's "Indigo" (latest version of freedoom2.wad MAP04). 

Are you sure it's OPL? Please check your settings, these clips don't sound like OPL to me. Are you using the latest version of DSDA-Doom? Recently there was an update to OPL.

**Comment by unithecutie** [comment]
I'm using DSDA-Doom 0.27.2 with a very recent Freedoom commit (I made that music credits list by the way!) - Freedoom includes a custom DMXOPL if I recall correctly. I'll re-record the first video with where it's been moved.

"Soviet Porno" was moved to MAP10, it was MAP04 in 0.12.1.

This is Indigo.
https://www.youtube.com/watch?v=Lfh2m8BgRcs
and this is Soviet Porno.
https://www.youtube.com/watch?v=LJRJvWm4fW0

**Comment by rfomin** [comment]
> "Soviet Porno" was moved to MAP10, it was MAP04 in 0.12.1.

Right, I'm using 0.12.1

Still, are you sure you set OPL? It sounds different to me.

**Comment by unithecutie** [comment]
I'm sure I set OPL - like I said, Freedoom uses a custom OPL instruments set.
I don't think it's in 0.12.1 but I'll check right now.

**Comment by unithecutie** [comment]
Still the same issue with 0.12.1, it skips notes.

https://github.com/kraflab/dsda-doom/assets/139153158/efa7799e-313a-4a05-8157-4b6b85692bc1

**Comment by unithecutie** [comment]
I can provide a credits list to go off of if you need it for 0.12.1 too. The one on Doomwiki is constantly updated to the Git page.

**Comment by rfomin** [comment]
Are you running Windows? If so, please try this build:  [dsda-doom-0.27.2-win64.zip](https://github.com/kraflab/dsda-doom/files/13234139/dsda-doom-0.27.2-win64.zip)

**Comment by unithecutie** [comment]
That fixed it somehow..? What?

**Comment by rfomin** [comment]
> That fixed it somehow..? What?

Build works? I made a few changes. Thanks for testing!

**Comment by unithecutie** [comment]
Yeah, hold on I'll get a re-recording of "Soviet Porno" now.

**Comment by unithecutie** [comment]
https://github.com/kraflab/dsda-doom/assets/139153158/6e3936e5-a79a-4c33-802f-20fb82b48433
