### ISSUE TITLE
Issue with cmake and libzip,  not able to install on Fedora 39

### ISSUE THREAD

**Issue by Contmotore** [kraflab/dsda-doom#440]
I followed the installation instructions for Linux(Fedora 39) as given in the INSTALL file, but when I try to run cmake I get the following error:

```
-- The C compiler identification is GNU 13.2.1
-- The CXX compiler identification is GNU 13.2.1
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for stricmp
-- Looking for stricmp - not found
-- Looking for strnicmp
-- Looking for strnicmp - not found
-- Looking for getopt
-- Looking for getopt - found
-- Looking for mmap
-- Looking for mmap - found
-- Looking for CreateFileMapping
-- Looking for CreateFileMapping - not found
-- Looking for strsignal
-- Looking for strsignal - found
-- Looking for mkstemp
-- Looking for mkstemp - found
-- Looking for sys/wait.h
-- Looking for sys/wait.h - found
-- Looking for unistd.h
-- Looking for unistd.h - found
-- Looking for asm/byteorder.h
-- Looking for asm/byteorder.h - found
-- Looking for dirent.h
-- Looking for dirent.h - found
-- Performing Test HAVE_WALL
-- Performing Test HAVE_WALL - Success
-- Performing Test HAVE_WWRITE_STRINGS
-- Performing Test HAVE_WWRITE_STRINGS - Success
-- Performing Test HAVE_WUNDEF
-- Performing Test HAVE_WUNDEF - Success
-- Performing Test HAVE_WTYPE_LIMITS
-- Performing Test HAVE_WTYPE_LIMITS - Success
-- Performing Test HAVE_WCAST_QUAL
-- Performing Test HAVE_WCAST_QUAL - Success
-- Performing Test HAVE_WPOINTER_ARITH
-- Performing Test HAVE_WPOINTER_ARITH - Success
-- Performing Test HAVE_WNO_UNUSED_FUNCTION
-- Performing Test HAVE_WNO_UNUSED_FUNCTION - Success
-- Performing Test HAVE_WNO_SWITCH
-- Performing Test HAVE_WNO_SWITCH - Success
-- Performing Test HAVE_WNO_SIGN_COMPARE
-- Performing Test HAVE_WNO_SIGN_COMPARE - Success
-- Performing Test HAVE_WNO_FORMAT_TRUNCATION
-- Performing Test HAVE_WNO_FORMAT_TRUNCATION - Success
-- Performing Test HAVE_WNO_MISSING_FIELD_INITIALIZERS
-- Performing Test HAVE_WNO_MISSING_FIELD_INITIALIZERS - Success
-- Performing Test HAVE_WABSOLUTE_VALUE
-- Performing Test HAVE_WABSOLUTE_VALUE - Success
-- Performing Test HAVE_WNO_POINTER_SIGN
-- Performing Test HAVE_WNO_POINTER_SIGN - Success
-- Performing Test HAVE_WDECLARATION_AFTER_STATEMENT
-- Performing Test HAVE_WDECLARATION_AFTER_STATEMENT - Success
-- Performing Test HAVE_WBAD_FUNCTION_CAST
-- Performing Test HAVE_WBAD_FUNCTION_CAST - Success
-- Performing Test HAVE_FFAST_MATH
-- Performing Test HAVE_FFAST_MATH - Success
-- Performing Test HAVE_FP_FAST
-- Performing Test HAVE_FP_FAST - Failed
-- Found OpenGL: /usr/lib64/libOpenGL.so (Required is at least version "2.0")  
CMake Warning at cmake/Findlibzip.cmake:73 (message):
  pkg-config is unavailable and libzip seems to be static, link failures are
  to be expected.

  Set `libzip_LINK_LIBRARIES` to a list of libraries libzip depends on.

  Set `libzip_LINK_DIRECTORIES` to a list of directories to search for
  libraries in.
Call Stack (most recent call first):
  CMakeLists.txt:113 (find_package)


CMake Error at /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find libzip (missing: libzip_LIBRARY libzip_INCLUDE_DIR)
Call Stack (most recent call first):
  /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:600 (_FPHSA_FAILURE_MESSAGE)
  cmake/Findlibzip.cmake:82 (find_package_handle_standard_args)
  CMakeLists.txt:113 (find_package)


-- Configuring incomplete, errors occurred!
```
pkg-config appears to be installed as well as libzip.

I'm not very familiar with compiling, I searched the internet a lot, but couldn't find a solution.

I tried the following command, but that didn't work either:
`cmake .. -DZLIB_INCLUDE_DIR=/usr/lib/ -DZLIB_LIBARY=/usr/lib/libz.so.1 -DCMAKE_BUILD_TYPE=Release`

**Comment by mikeday0** [comment]
You probably need to also install `libzip-devel` and `libzip-tools`.

**Comment by Contmotore** [comment]
> You probably need to also install `libzip-devel` and `libzip-tools`.

Thanks! I was missing the `libzip-devel` one.

I was getting the same kind of error for SDL_mixer, so had to install `SDL2_mixer-devel` as well.  Turns out I just needed to install some  `-devel`  packages.

However, when trying to create a rpm I get the following message:
`make: *** No rule to make target 'rpm'.  Stop.`

So, not sure what to do here. Should I create a new topic for this?

**Comment by mikeday0** [comment]
As a general rule, if you are building from source you will need the `-devel`/`-dev` versions of any required libraries.

I don't think you should need to make an rpm. After `cmake` creates all the build files, all you should need to do is navigate to the `build` directory and then run:
1. make
2. sudo make install

**Comment by Contmotore** [comment]
> As a general rule, if you are building from source you will need the `-devel`/`-dev` versions of any required libraries.
> 
> I don't think you should need to make an rpm. After `cmake` creates all the build files, all you should need to do is navigate to the `build` directory and then run:
> 
> 1. make
> 2. sudo make install

I'm also not sure if I need an rpm. My goal is to have several versions installed so I can open my old saved games.

I've successfully compiled the build and I'm able to run dsda-doom from the build directory. But as expected, when doing a make install, it overwrites the current version. I guess I can just copy the files to a custom directory and create a PATH for it? What would be the best way to approach this?

**Comment by kraflab** [comment]
If there's a required package missing in the doc, feel free to open a PR and update it (or if there are other confusing / out of date elements there).

**Comment by mikeday0** [comment]
> I'm also not sure if I need an rpm. My goal is to have several versions installed so I can open my old saved games.
> 
> I've successfully compiled the build and I'm able to run dsda-doom from the build directory. But as expected, when doing a make install, it overwrites the current version. I guess I can just copy the files to a custom directory and create a PATH for it? What would be the best way to approach this?

First I would uninstall the dsda-doom that you installed previously. Navigate to your build directory and run:
`xargs rm < install_manifest.txt` (may need `sudo`)

You can specify CMAKE_INSTALL_PREFIX when you run the configure step like so:
`cmake -DCMAKE_INSTALL_PREFIX=/path/to/desired/install/location ..`

After that, `make install` will install to `/path/to/desired/install/location` instead of the default `/usr/local`.

You will want to use the `-save`, `-data` and `-config` arguments to specify a non-default save directory, data directory and config file for each version.

Finally you can make a bunch of custom aliases in your .bashrc (or equivalent):
`alias dsda-doom0.27="/path/to/0.27/binary -save /path/to/0.27/savedir -data /path/to/0.27/datadir -confg /path/to/0.27/config"`
... etc

Then you can run that specific version by invoking `dsda-doom0.27`. 

This will all probably require some experimentation to get it working exactly the way you want, as is the Linux way. Happy tinkering!

**Comment by Contmotore** [comment]
Many thanks! Will tinker around some more.

I'm closing this topic now, because we went way off topic and I was able to successfully build and install the game from source.

**Comment by Contmotore** [comment]
Many thanks! Will tinker around some more.

I'm closing this topic now, because we went way off topic and I was able to successfully build and install the game from source.
