### ISSUE TITLE
Hexen: using a banishment device ends up using all artifacts

### ISSUE THREAD

**Issue by kitchen-ace** [kraflab/dsda-doom#448]
Any time you try to use a [banishment device](https://doomwiki.org/wiki/File:Hexen_BanishmentDevice.png) in Hexen, you use all artifacts you have. Vanilla Hexen does have a "use all artifacts" hotkey so maybe the two are being conflated somehow.

DSDA-Doom 0.27.4 on Linux, tested with a fresh config, doesn't matter if you use the artifact from a hotkey or the artifact bar.

**Comment by kraflab** [comment]
Fixed here: https://github.com/kraflab/dsda-doom/commit/3c1eef48aef5e1f38a1078cea592fefcf2f39381
Thanks for the report!
