### ISSUE TITLE
Add Line_Horizon feature both in GL and Software mode.

### ISSUE THREAD

**Issue by HatredDoge** [kraflab/dsda-doom#451]
Different techniques doesn't get this effect working, and not even NodeBuilder can achieve the line horizon effect. By the way, Eternity and ZDoom action codes 450 and 337 can barely get this effect with a non-textured wall. But, using this techniques just doesn't optimize map making.

**Comment by kraflab** [comment]
Please follow the suggestions when creating issues to avoid wasting time.

**Comment by HatredDoge** [comment]
> Please follow the suggestions when creating issues to avoid wasting time.

Where are those suggestions?

**Comment by kraflab** [comment]
They're in the template when you open an issue, which in this case would have been a feature request.

**Comment by HatredDoge** [comment]
> They're in the template when you open an issue, which in this case would have been a feature request.

Sorry, I'm new in these places.

**Comment by kraflab** [comment]
No worries, in this case there would be hundreds of issues open if every individual special action or other feature of gzdoom got one. I don't manage this kind of stuff on GitHub and discuss things on discord instead.
