### ISSUE TITLE
No -savedir flag?

### ISSUE THREAD

**Issue by mooreye** [kraflab/dsda-doom#454]
In prboom+ there was a `-savedir` flag that allowed to set custom save directory for savegame files. This was useful, it would be very nice to include it here too.

Same with `-shotdir` for screenshot dir.

**Comment by mooreye** [comment]
Just discovered that there is is a `-save` flag (undocumented in `-help`'s output) however it doesn't seem to work - saves are still saved in `./dsda_doom_data/doom/` subdirectory (for `doom.wad`)

**Comment by kraflab** [comment]
You probably have the setting "organize my saves" turned on, in which case the saves are put in the data directory. There's a parameter to change the data directory, or you could disable that setting.

**Comment by mooreye** [comment]
> You probably have the setting "organize my saves" turned on, in which case the saves are put in the data directory. There's a parameter to change the data directory, or you could disable that setting.

Whoa, I don't think I would've figured that out myself. If `-save` commandline option is given explicitly, I think it should ignore this setting.

**Comment by kraflab** [comment]
> (undocumented in `-help`'s output)

I see it in the -help response. Could you confirm?

**Comment by mooreye** [comment]
> > (undocumented in `-help`'s output)
> 
> I see it in the -help response. Could you confirm?

Okay, I see it too. Must have missed it somehow before.
Still, I think it would be more intuitive if `-save` commandline option is given explicitly, it should ignore this setting.

**Comment by kraflab** [comment]
I'm not completely convinced. I understand what you're saying but one might also expect that this command would act like the data directory arg (i.e., continue organizing my saves, but organize them somewhere else), which is a different behavior entirely.

**Comment by mooreye** [comment]
> I'm not completely convinced. I understand what you're saying but one might also expect that this command would act like the data directory arg (i.e., continue organizing my saves, but organize them somewhere else), which is a different behavior entirely.

Okay, that makes sense. Closing this then.
