### ISSUE TITLE
Lost Souls don't have health bar

### ISSUE THREAD

**Issue by mooreye** [kraflab/dsda-doom#455]
Is this intentional?

**Comment by mooreye** [comment]
Probably all monsters without COUNTKILL bit have this, why?

**Comment by kraflab** [comment]
I can't comment on intention because this feature predates the port, but you are correct that it only renders a health bar if countkill is set.

**Comment by kraflab** [comment]
I don't use this feature and don't have a strong opinion on this change but my default stance is always on not changing things. If you want to change this, raise the topic on the discord and see if others agree, then I can fix it easily.

**Comment by mooreye** [comment]
What is the link to discord?
