### ISSUE TITLE
Resample quality?

### ISSUE THREAD

**Issue by mirodno** [kraflab/dsda-doom#456]
Greetings. Does DSDA-Doom features an ability to change resample quality? If not, is it possible to implement it? From what i found in config, there is no way to change resample quality, you can only change samplerate itself, which is not exactly what i want.

There is a problem with default 11025 sounds on 44100Hz rate, they are too harsh, incorrect in some places (too quiet or too loud) and some of custom sounds (PSX Doom ones most notorious) even have clipping issues! Yes, you can change rate to 11025, so all of those problems will disappear, but it'll also downsample all of high quality playback such as MIDI (with the exception of external midi device), encoded music, high-quality sounds etc.

Implementing any sort of resampler similar to one in GZDoom will solve a problem while keeping all of high quality stuff.

**Comment by kraflab** [comment]
This is the kind of thing that will only exist if you manage to find a dedicated person to implement it.

**Comment by mirodno** [comment]
Sad. It has been 25 years since PrBoom's first release, and its audio mess still persists in all of its descendants. Guess no one was dedicated enough through all this years.

The only solution for now is using properly resampled sounds as mods.

What are possible solutions to resampling-on-fly problems? OpenAL implementation or something else? Need to know, because i want to try something, but i don't even know where to start. I'm not a coder, but audio thingie isn't that alien to me at least.

**Comment by kraflab** [comment]
I wouldn't know where to start either - don't know much about audio. You could reach out to the Woof devs since they added OpenAL to get some insights. The main distinction with pr+ and its descendants is the viddump feature where the port needs to be able to convert demos to video files, which currently involves a lot of low level data stream management. Any changes need to not break that process.

**Comment by mirodno** [comment]
Woof did it? I missed it somehow. Thanks for hint, I'll check their source code.

**Comment by rfomin** [comment]
I suggest you consider the https://openal-soft.org/openal-extensions/SOFT_loopback.txt extension for videodump support. It would also be nice to switch to [libsndfile](https://github.com/libsndfile/libsndfile) for OGG/FLAC/MP3 music and WAV sounds.

The Woof sound system is quite different from the PrBoom+, not much can be taken directly from there.

**Comment by mirodno** [comment]
Thank for help and suggestions, everyone!

**Comment by kraflab** [comment]
Closing this one as there hasn't been any action in 6 months and I don't consider it an "issue" that needs attention. If a future contributor is interested, feel free to look into the topic or reach out to me about it.
