### ISSUE TITLE
Submit Flatpak to Flathub

### ISSUE THREAD

**Issue by spazzylemons** [kraflab/dsda-doom#460]
I've created a mostly complete Flatpak repository for DSDA-Doom. Flatpak is a system for packaging sandboxed Linux applications for easy installation. Flatpak packages are primarily uploaded and downloaded from [Flathub](https://flathub.org/), which allows Linux users to install applications that they might not have access to via a package manager, without needing to compile anything. My motivation for making this was actually so that I could install DSDA-Doom on my Steam Deck, since the preferred method of installing non-Steam apps on the Steam Deck is through Flatpak due to system packages being reset after each update. I've outlined what I think would need to be done before submitting the package to Flathub in a README file in the repository: https://github.com/spazzylemons/DSDADoom-Flatpak. The main reason I ask here instead of submitting it myself is because it's preferred that the app authors maintain their own packages on Flathub. There's one small change to the code that allows the application to run under the Flatpak sandboxed filesystem that I made a pull request for: #461

**Comment by kraflab** [comment]
Closing as the related change has been merged. If there are other things needed feel free to submit more requests.

**Comment by mooreye** [comment]
@spazzylemons Is there everything ready now for submitting to Flathub? Have you by any chance already started getting dsda-doom onto Flathub?

**Comment by mooreye** [comment]
@spazzylemons ping

**Comment by spazzylemons** [comment]
I haven't uploaded it because it's preferred that the application maintainer do that, from what I understand. Last I worked on this, I was able to build it locally. I could see about uploading it myself if you'd like.

**Comment by mooreye** [comment]
> I haven't uploaded it because it's preferred that the application maintainer do that, from what I understand. Last I worked on this, I was able to build it locally. I could see about uploading it myself if you'd like.

@spazzylemons The maintainer once expressed that he doesn't intend to do so: https://github.com/kraflab/dsda-doom/issues/251#issuecomment-1458562423

**Comment by spazzylemons** [comment]
I'll look into getting the Flatpak package set up soon

**Comment by mooreye** [comment]
> I'll look into getting the Flatpak package set up soon

Any news on this?

**Comment by spazzylemons** [comment]
Sorry that I forgot about this. I've gotten around to making a PR to add this to Flathub. Most of the issues have been resolved with it, but according to the Flathub maintainers, the [metainfo](https://github.com/spazzylemons/flathub/blob/io.github.kraflab.DSDA-Doom/io.github.kraflab.DSDA-Doom.metainfo.xml) and [screenshots](https://github.com/spazzylemons/flathub/tree/io.github.kraflab.DSDA-Doom/images) should be a part of this repository

**Comment by Pedro-Beirao** [comment]
Well then, you can make a PR to add those.
