### ISSUE TITLE
Support Raven MIDI pack for Heretic

### ISSUE THREAD

**Issue by mooreye** [kraflab/dsda-doom#463]
https://www.doomworld.com/forum/topic/114080-raven-midi-pack-project-complete/

Crispy-Heretic supports this MIDI pack, it would be great if DSDA-Doom did too.

**Comment by kraflab** [comment]
What doesn't work exactly? Dsda-doom has musinfo support as well.

**Comment by mooreye** [comment]
I loaded this as a `-file` after `-iwad heretic.wad`. There should be a different music track in E3M1 than in E1M1 (this midi pack replaces duplicates), but I can hear that they are the same.

Here someone mentions this doesn't work too: https://www.doomworld.com/forum/topic/114080-raven-midi-pack-project-complete/?page=7&tab=comments#comment-2596537

Doom Wiki has something to say about this too: https://doomwiki.org/wiki/Raven_MIDI_Pack

```
Although technically vanilla-compatible in that all tracks can be converted to MUS format and used in Heretic levels, the tracks from the pack will only be heard if played in a port that can read the [EMAPINFO or ZMAPINFO](https://doomwiki.org/wiki/MAPINFO) lumps, or otherwise allows to map Heretic map slots to the corresponding MUS_ExMy lump if present, such as [Crispy Heretic](https://doomwiki.org/wiki/Crispy_Doom). This is because instead of having duplicated music lumps (like how registered Doom has D_E1M7, D_E2M5, and D_E3M5 all containing the same track), Heretic reuses the same lump (like the fourth episode of Ultimate Doom reuses tracks associated with levels from the first three episodes). Since this behavior is hardcoded, there is no way around this, short of splitting the pack into several episode-specific replacements.
```

Does this mean DSDA-Doom doesn't support these lumps?

**Comment by kraflab** [comment]
No, the problem was musinfo default track support. Fixed here: https://github.com/kraflab/dsda-doom/commit/32358cb53031a9363c56709da7aacecb3d8690ac
