### ISSUE TITLE
Strange warping/bending effect when turning on opengl full screen mode in v0.27.5

### ISSUE THREAD

**Issue by doomdbhai** [kraflab/dsda-doom#464]
See below for comparison:

[https://1drv.ms/f/s!ApSZbWSxxNFzvBp8MwTbKx8BI5E-?e=gRM7qd](https://1drv.ms/f/s!ApSZbWSxxNFzvBp8MwTbKx8BI5E-?e=gRM7qd)

when using opengl renderer in full screen mode and/or exclusive full screen mode, strange "bend" effect occurs with the graphics when I am turning. This occurs in both 0.26 and 0.27. Does not occur when NOT using full screen mode.

**Comment by kraflab** [comment]
This looks like an issue on your end. I suggest looking for help either on the forums or on the discord. If it ends up being a problem with the port, then we'll take a closer look, but I would start there.
