### ISSUE TITLE
Sigil II with Thorr soundtrack crashes DSDA-Doom on exit

### ISSUE THREAD

**Issue by mooreye** [kraflab/dsda-doom#465]
Romero's Sigil II with Thorr's MP3 soundtrack crashes the game when I exit it:

```
mad_registersong succeed. bitrate 320000 samplerate 48000
The game has crashed!
Please report the following information: Segmentation fault (0x0000)
```

However it seems to crash only when you manually quit Dsda-doom, playing it works fine.
Without the MP3 soundtrack no issue occurs.

**Comment by spazzylemons** [comment]
I'm able to reproduce this even with a single PWAD containing a single MP3. There seems to be a race condition where the MP3 music player is destroyed while still being used in the audio callback.

**Comment by kraflab** [comment]
Can't reproduce this. If this is a race condition it might just not happen on my hardware, in which case someone who can reproduce it would need to debug it and find the error.

**Comment by mooreye** [comment]
This stopped occurring for me on Fedora 41 with dsda-doom v0.28.2
