### ISSUE TITLE
OPL does not handle pitch bends in MIDIs

### ISSUE THREAD

**Issue by unithecutie** [kraflab/dsda-doom#472]
OPL ignores pitch bends in MIDIs completely and makes them sound very odd: Here's an example with "Workout" by Korp.

https://www.youtube.com/watch?v=mxh3UhRyi3s

The charango lead in the MIDI pitch bends a lot; here's an example with Roland GM.
(converted to MP4 so I can send it here)

https://github.com/kraflab/dsda-doom/assets/139153158/09f8c8c7-ab58-40a9-a142-f07c73efed9b

**Comment by rfomin** [comment]
> OPL ignores pitch bends in MIDIs completely and makes them sound very odd: Here's an example with "Workout" by Korp.

Does it work in Chocolate/Crispy Doom?

Maybe it is supposed to work that way: `Only the MSB of the pitch bend value is considered: this is what Doom does.` https://github.com/chocolate-doom/chocolate-doom/blob/72d9e9318c4ccc61dab29bb9cc30bc8a9a93266d/src/i_oplmusic.c#L1231-L1232

Also please provide more info, which Fredoom version, which level etc.

**Comment by unithecutie** [comment]
Oh, then it's supposed to work that way.
It's one of the later autobuilds.
