### ISSUE TITLE
More flexibility according to what gets compiled-in?

### ISSUE THREAD

**Issue by aznlir88** [kraflab/dsda-doom#474]
Probably, like 99,999% it's just me but personally I prefer to be able to choose what I want to compile into a program when I build it from source code.

In dsda-doom we can only not compile in support for vorbis, portmidi, mad and like a few more mostly sound related. While in prboom-plus we were able to not compile in opengl and a few more. Not talking about silly stuff but for example if someone would allow me not to compile in everything TAS related I would be very glad about that.

I do not expect much support here as people usually do not care but... maybe someone else also prefer to have more control over what goes into the program.

**Comment by kraflab** [comment]
Not planning on making any changes to the current approach.
