### ISSUE TITLE
Removal of "comperr_zerotag" support leading to bugs in some wads.

### ISSUE THREAD

**Issue by gorxen** [kraflab/dsda-doom#479]
Hey guys, apparently the removal of "comperr_zerotag" support is the cause of some door bugs I've encountered in MANY of the popular chillax-v9.7.3.wad maps.

Many of the doors that require triggering via the use key won't open. Please refer to this post I made in the Doomworld forums to fully understand the issue. 

[https://www.doomworld.com/forum/topic/143168-is-this-a-dsda-door-bug/](url) 

So I'm humbly asking for it to be added back, thanks <3

**Comment by kraflab** [comment]
The thread you linked already has info about the context of its removal and my future plans to deal with it. We don't need an issue open for this as it's an intended change and the maps in question are themselves broken and incompatible with the engine.
