### ISSUE TITLE
[Feature Request] Autosave feature

### ISSUE THREAD

**Issue by HugeTaffer** [kraflab/dsda-doom#480]
I usually like to not bother with saves as I feel it cheapens out the experience, but for particularly difficult maps I'd love to have convenient autosaves either at the start of the map or even better, everytime you pick up a key. Will do wonders for my manual save hating habits.

Also the discord link seems to have expired, you should probably look into it :)

**Comment by kraflab** [comment]
https://github.com/kraflab/dsda-doom/commit/2e141f39731c6a290ac56d8b0fcc526db7181b52
