### ISSUE TITLE
SIGIL E5M8 ends prematurely

### ISSUE THREAD

**Issue by JimmyZD** [kraflab/dsda-doom#481]
Hi!

It seems as though SIGIL E5M8 is coded to finish the map after a boss monster (of any type) is killed.

Ways to reproduce:
- Warp to E5M8, and type TNTEM. The level should end after a few seconds.
- Warp to E5M8, use IDFA to give all weapons, then noclip to kill either the spider mastermind or cyberdemon. The level should end after a few seconds.
- Warp to E5M8, use IDFA and kill all barons of hell on the map (there is only one on HNTR - he is located in the southern monster box, at (192, -368)). The level should end after a few seconds.

This map should not have any boss actions attached, as killing the boss monsters should have no effect on the level's endgame - the map contains an exit teleporter you can reach potentially without killing anything.

Tested with latest DSDADoom 0.27.5 binary (Windows 10 PC) and the v1.21 release of SIGIL straight from Romero.com.

**Comment by kraflab** [comment]
Did you use the compatible version of the wad? Something like `SIGIL_COMPAT_v1_21.wad` I think.

**Comment by JimmyZD** [comment]
No, this was using `SIGIL_v1_21.wad`, with the maps occupying the E5* slots instead of E3*.

**Comment by fabiangreffrath** [comment]
The special casing for the boss death action is missing from Sigil's embedded UMAPINFO lump. Try to load this lump in addition (rename to `umapinfo.lmp` before).

https://github.com/fabiangreffrath/woof/blob/master/autoload/sigil_v1_21.wad/umapdef.lmp

**Comment by kraflab** [comment]
You either need to use the compatible version of the wad or replace the umapinfo lump as indicated. Or ask Romero to fix his wad 😉
