### ISSUE TITLE
Provide setting for divorced freelook / vertical auto-aim

### ISSUE THREAD

**Issue by lemming104** [kraflab/dsda-doom#489]
I've been playing around with the recent commit https://github.com/kraflab/dsda-doom/commit/f891737984ec453a892fc9bd9fac63926a1cf2eb, and it feels like enabling freelook suppresses vertical auto-aim.  I only see the one option in the settings menu for enabling/disabling freelook, and skimming through the commit, it looks like they're controlled by the same setting/cvar?

I like playing with freelook on, but only so I can see things that are well above or below the normal field of view (for example, the "pit" toward the end of Doom E1M2).  Is it possible to divorce these two behaviors into separate settings?

**Comment by kraflab** [comment]
No, I don't want to split these - they were split before and the PR removed the split. It simplifies things and also reflects the MAPINFO behavior, and is also one step to removing these behavior-altering "map correction" settings from the menu. For the "exploring the scene" use case, one can toggle it on and off as needed.

**Comment by mooreye** [comment]
It should at least be possible to enable freelook only for Heretic/Hexen but not for Doom, since in Heretic/Hexen vertical aim was a part of the vanilla gameplay but not in Doom.

**Comment by mooreye** [comment]
Also, this kinda makes me sad because previously you could use freelook to better explore the map without altering vanilla gameplay (cheating). Now, freelook is definitely cheating because you can shoot shootable switches from unintended places.

**Comment by Pedro-Beirao** [comment]
> Now, freelook is definitely cheating because you can shoot shootable switches from unintended places.

The freelook toggle isnt on itself cheating. Using it to shoot shootable switches from unintended places is cheating tho. (considering casual play, not speedrunning)

When I want to explore something, I may toggle it, and will toggle it back right after.
Separate toggles would give us the weird behaviour of being able to freelook, without the shots going to where we are looking, so I agree that this change should stay.

As for heretic and hexen, in a future menu update, we might add an option to always allow freelook in those games
