### ISSUE TITLE
Boom HUD font shadows

### ISSUE THREAD

**Issue by NightFright2k19** [kraflab/dsda-doom#499]
For some colors of the Boom fullscreen HUD, the shadows are colorized instead of being black/dark. [I have reported a similar issue for Woof!](https://www.doomworld.com/forum/post/2815052), where it has been adjusted recently.

![boomhud_now](https://github.com/user-attachments/assets/6adbefb1-91db-4dc9-9ee9-3140017ae554)

For this port, the colors red, yellow and blue would be affected. White and green already have dark shadows. While it might seem trivial, it is a matter of consistency and would improve legibility (depending on the background).

**Comment by kraflab** [comment]
They were changed to be colorized on purpose, so this isn't an error. The color ranges are also configurable by users, so it should be possible to use black shadows if you want.
