### ISSUE TITLE
Distribute Windows binaries on GitHub Releases for convenience and automation

### ISSUE THREAD

**Issue by Calinou** [kraflab/dsda-doom#500]
Could you look into distributing the Windows releases on GitHub Releases? This would make it possible to hotlink the downloads, and therefore add dsda-doom to [scoop-games](https://github.com/Calinou/scoop-games). Right now, I can't automate its installation because Google Drive links are not hotlinkable. Thanks in advance :slightly_smiling_face:

**Comment by Borfie** [comment]
I second this, for some strange reason opening the folder on Google Drive makes me unable to interact with it in any way, the download button shows as not available. Having it on Github would make this very much easier

**Comment by kraflab** [comment]
Sure, I'll do this for future releases and have added one retroactively to 0.28.
