### ISSUE TITLE
Crash to desktop when pressing Num Lock

### ISSUE THREAD

**Issue by hfc2x** [kraflab/dsda-doom#502]
I'm on Fedora 40 (KDE, Wayland), and everything seems to work normally. Except I can't type with the Numpad.

Was trying to set an FPS limit to stop my GPU from coil whining lol. Typing the numbers with the Numpad did nothing, and trying to press Num Lock caused the game to crash full-stop. Typing the numbers with the number row works fine.

Didn't even need to press Num Lock, since it was already on anyways, but doing this crashes the game every time without fail.

Running DSDA-Doom from the terminal gives this output:
```
The game has crashed!
Please report the following information: Segmentation fault (0x0000)
```

**Comment by fabiangreffrath** [comment]
This fixes it for me:

```patch
--- a/prboom2/src/m_menu.c
+++ b/prboom2/src/m_menu.c
@@ -4686,7 +4686,7 @@ static dboolean M_SetupCommonSelectResponder(int ch, int action, event_t* ev)
         if (gather_count >= MAXGATHER)
           return true;
 
-        if (!isdigit(ch) && ch != '-')
+        if (!isdigit((unsigned char)ch) && ch != '-')
           return true; // ignore
 
         /* killough 10/98: character-based numerical input */
```

Quote from `isalpha(3)`:

`These functions check whether c, which must have the value of an unsigned char or EOF, ...`

**Comment by kraflab** [comment]
https://github.com/kraflab/dsda-doom/commit/8e6d9c0b457352a39470d00543b34e06ca2d6cfe thanks!
