### ISSUE TITLE
Sprite-clipping in hardware renderer equal to software renderer possible?

### ISSUE THREAD

**Issue by Meerschweinmann** [kraflab/dsda-doom#508]
Hello.

Is it possible to modify the hardware renderer to handle sprite clipping equal to the software renderer?

DSDA's hardware renderer has the possibility to emulate the paletted color and original DOOM lightning look.
So it would be fine when it could do the sprite clipping in hardware-mode as in software-mode as well.

Here are two pictures of a Revenant in a low ceiling room, where the poor Revenant's head is cut in hardware-mode.

![doom00](https://github.com/user-attachments/assets/ad84e865-ff58-4e0b-8448-a3caa291bdcb)
![doom01](https://github.com/user-attachments/assets/c9f2c925-5877-463f-aec6-162eb2ec1b5e)

Greetings

**Comment by kraflab** [comment]
It's technically possible but not trivial. It would need a dedicated opengl expert to work on this, and we don't currently have one. As it's a known / accepted difference, I will close the issue, but if someone is interested in working on this in the future feel free to open a PR.
