### ISSUE TITLE
a way to change brightness/gamma/contrast levels?

### ISSUE THREAD

**Issue by Sol1vaN** [kraflab/dsda-doom#510]
there's a way to change the brightness/gamma/contrast in dsdadoom?
i've commented this on discord, but only a guy says "press F11"
but it only raises the gamma, and I want to low this value (or lowering gamma/contrast).

via menu i cant find an option
nor vía console command

**Comment by kraflab** [comment]
dsda-doom only supports the original light levels, and I don't have any plan to change that. By the way, there's no need to post on both the discord and on here with questions - I read every post on the discord channel.

**Comment by Sol1vaN** [comment]
that's sad man.
i cant see why you dont let the people change this, is very common today, on all source ports.
dsda is incredible source port, that's why i want it.
anyway, many thanks for your reply.

**Comment by markus-zhang** [comment]
Ah that's sad, I wish I knew it from the beginning.
