### ISSUE TITLE
turn off auto switch weapon when pickup

### ISSUE THREAD

**Issue by Sol1vaN** [kraflab/dsda-doom#511]
hi there,
there's a way to disable this feature?
i don't like it and i want to disable it.
on "quality of life" menu there is an option called something like:
"boom weapon auto swithc"
but this do nothing, still the weapons change when i pickup one.

dsda have an way to change correctly this?
or via console command, editing a cfg file at least?

**Comment by kraflab** [comment]
Boom weapon autoswitch occurs when running out of ammo, so that's a separate thing. I think it's worth adding this feature to the casual play settings, although it won't be available while demo recording.

**Comment by Pedro-Beirao** [comment]
Done in https://github.com/kraflab/dsda-doom/pull/541
