### ISSUE TITLE
dsda-doom 28.1 crashes loading savegame (probably saved by old dsda-version)

### ISSUE THREAD

**Issue by bjoerng** [kraflab/dsda-doom#522]
Loading savegames with version 28.1only works if created by the same version.

Loading my savegame resulst in dsda segfaulting.

Tried this with version 28.1 in Debian an the Windows Binary provided here. I will attach the save-file which crashes dsda when loaded. But this is not the only one. If another one is needed, just let me know.
[dsda-doom-savegame0.dsg.zip](https://github.com/user-attachments/files/17441138/dsda-doom-savegame0.dsg.zip)

**Comment by kraflab** [comment]
Saves aren't always cross-version compatible so this is an expected issue.
