### ISSUE TITLE
better feedback to end user

### ISSUE THREAD

**Issue by xawesomecorex** [kraflab/dsda-doom#553]
Dude, your "missing IWAD" error log in command line sucks ass. You have to give more information than that especially when the user, like me, has no idea where to drop Doom 1 & 2's main wads or even how to point it to my Steam installation because you don't even have a man page, or even explain any of that on the github. Not to mention if I were new to running doom on a source port I wouldn't even know that "IWAD" means doom2.wad, freedoom.wad ect. because "IWAD" is incredibly and unacceptably non descript. Please, for five fucking seconds stop thinking like the dev and think like the user, because it's unreasonable to expect the end user to know what the devs know *AND* all it takes is a simple IF statement on your end.

**Comment by Pedro-Beirao** [comment]
You are mad at a 24 year old error message, and devs that work on this on their free time, chill.

But yes that error message could be more descriptive

**Comment by abilkhairseilov** [comment]
```cmd
dsda-doom.exe -iwad "your iwad" -file "some file or pwad"
```

IWADs refer to the main resource files

PWADs refer to the files you add, like mods, maps or textures

Like previously said, the error log is 24 years old. At this stage of Doom modding, source port developers assume that you know how to link files, pwads and etc.

But I do agree that there should be a tutorial for beginners. Matter of fact, you can help out others and make a PR to add stuff to the readme file.

**Comment by xawesomecorex** [comment]
@Pedro-Beirao it's a 24 year old bug and you guys hadn't thought to correct that? It should be just be an if statement. for example:  if ~/home/thisguy/.dsda/doom.wad is not true prnt "put required doom files here dummy". I am coming off of covid, constantly cranky at the moment and perhaps should reign the anger in a little but I don't think it's much to ask for some form of error feedback.

**Comment by fabiangreffrath** [comment]
> but I don't think it's much to ask for some form of error feedback.

You are not asking, just shouting.

Your concern is understood, it's just that nobody in the past decades seemed to bother as much as you.

**Comment by xawesomecorex** [comment]
If by "nobody in the past decades" you mean prboom users they probably weren't as bothered because the needed documentation was likely on the webpage. where is your documentation?
