### ISSUE TITLE
Eviternity II crashes instantly

### ISSUE THREAD

**Issue by mooreye** [kraflab/dsda-doom#560]
WAD: https://eviternity.dfdoom.com/

```
$ dsda-doom  -iwad '_/files/doom2.wad' -file '_/files/eviternity2.wad'
dsda-doom v0.28.2 (https://github.com/kraflab/dsda-doom/)
dsda-doom is released under the GNU General Public license v2.0.
You are welcome to redistribute it under certain conditions.
It comes with ABSOLUTELY NO WARRANTY. See the file COPYING for details.

Playing: DOOM 2: Hell on Earth
 adding /home/user/.dsda-doom/_/files/doom2.wad
 adding /usr/share/dsda-doom/dsda-doom.wad
 adding /home/user/.dsda-doom/_/files/eviternity2.wad
Detected COMPLVL lump: 21
Loading DEH lump from /home/user/.dsda-doom/_/files/eviternity2.wad
Using data file directory: /home/user/.dsda-doom/dsda_doom_data/doom2/eviternity2

/usr/include/c++/14/bits/stl_vector.h:1130: std::vector<_Tp, _Alloc>::reference std::vector<_Tp, _Alloc>::operator[](size_type) [with _Tp = doom_mapinfo_special_action_t; _Alloc = std::allocator<doom_mapinfo_special_action_t>; reference = doom_mapinfo_special_action_t&; size_type = long unsigned int]: Assertion '__n < this->size()' failed.
The game has crashed!
Please report the following information: Aborted (0x0000)
```

Clean config, no autoloads, most recent version of Eviternity II, all other games work fine.

OS: Fedora 41
Installation method: DNF from official repository
dsda-doom version: 0.28.2

**Comment by Pedro-Beirao** [comment]
This was reported on discord by someone running Linux as well. They were able to fix it by building dsda-doom themselves. Its possible that DNF's build has some problem.

Could you try the appimage? https://github.com/kraflab/dsda-doom/releases/tag/v0.28.2

**Comment by fabiangreffrath** [comment]
Does Eviternity 2 have an mp3 soundtrack? This might well be the unpatched libmad.

**Comment by rfomin** [comment]
> Does Eviternity 2 have an mp3 soundtrack?

No, it's MIDI.

From the error message it looks like there is a problem in the MAPINFO parser (Eviternity II has DSDA-Doom MAPINFO variant). Maybe the problem is related to the C++ standard library?

**Comment by mooreye** [comment]
> This was reported on discord by someone running Linux as well. They were able to fix it by building dsda-doom themselves. Its possible that DNF's build has some problem.
> 
> Could you try the appimage? https://github.com/kraflab/dsda-doom/releases/tag/v0.28.2

Thanks. The appimage works fine. Guess I'll have to report the issue to Fedora maintainers.

**Comment by suve** [comment]
This should be fixed by [PR#561](https://github.com/kraflab/dsda-doom/pull/561). The reason this has only manifested in Fedora Linux is most likely because Fedora's default set of compiler flags includes code hardening (`-D_FORTIFY_SOURCE=3`, among others).

**Comment by Pedro-Beirao** [comment]
Lets keep this open until next release, so we can be sure DNF's build is fixed

**Comment by suve** [comment]
Updates for [Fedora 41](https://bodhi.fedoraproject.org/updates/FEDORA-2024-ae5ceb81d1) and [Fedora 40](https://bodhi.fedoraproject.org/updates/FEDORA-2024-e42f7d3e8e) are now available in the testing repository.

**Comment by mooreye** [comment]
Fedora's updated version solves the issue
